Add eeprom_contents thrift struct to CMake
Summary:
# Background
eeprom_contents thrift target is missing in fboss weutil CMake build system resulting in following error:
```
In file included from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/platform/weutil/FbossEepromParser.h:8,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/platform/weutil/FbossEepromParser.cpp:3:
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/platform/weutil/FbossEepromInterface.h:10:10: fatal error: fboss/platform/weutil/if/gen-cpp2/eeprom_contents_types.h: No such file or directory
   10 | #include "fboss/platform/weutil/if/gen-cpp2/eeprom_contents_types.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
e.g.
https://www.internalfb.com/sandcastle/workflow/909727124737145902

# Actions
* Add missing eeprom_contents target to CMake build system to fix the issue.

Reviewed By: KevinYakar

Differential Revision: D77164863

fbshipit-source-id: fbcffc6480585264caf34d89eabe91b14b616633