Fix missing reference in libsensor_service_utils
Summary:
P1663641366

```
FAILED: sensor_service_utils_tests
: && /usr/bin/c++ -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG  CMakeFiles/sensor_service_utils_tests.dir/fboss/platform/sensor_service/test/UtilsTest.cpp.o -o sensor_service_utils_tests  -Wl,-rpath,/var/FBOSS/tmp_bld_dir/installed/glog--TiS8L7XT-dpPvonq2U7ueP0LLGtKprnfwIBV9cK38M/lib64:/var/FBOSS/tmp_bld_dir/installed/gflags-rTRHsBCNJ1QPFhXYI6Cn8x-wcYeGrQFSs0Z0lQGKwJ8/lib:/var/FBOSS/tmp_bld_dir/installed/libunwind-c63vwue81b-g1PVdgyfRrkAm8NgyayrkapvA8lMj46w/lib  libsensor_service_utils.a  /var/FBOSS/tmp_bld_dir/installed/googletest-GXS04svCG6RIq2z2VZ5_jAU0UT7-sdLvT-zqexiGLLs/lib64/libgmock_main.a  /var/FBOSS/tmp_bld_dir/installed/googletest-GXS04svCG6RIq2z2VZ5_jAU0UT7-sdLvT-zqexiGLLs/lib64/libgmock.a  /var/FBOSS/tmp_bld_dir/installed/googletest-GXS04svCG6RIq2z2VZ5_jAU0UT7-sdLvT-zqexiGLLs/lib64/libgtest.a  libsensor_config_cpp2.a  libplatform_manager_service_cpp2.a  libplatform_manager_snapshot_cpp2.a  libplatform_manager_config_cpp2.a  libplatform_manager_presence_cpp2.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftcpp2.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftfrozen2.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftmetadata.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftanyrep.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthrifttype.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftprotocol.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftprotocol.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libasync.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libruntime.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libtransport.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/librpcmetadata.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libconcurrency.a  /lib64/libzstd.so  /var/FBOSS/tmp_bld_dir/installed/wangle/lib/libwangle.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthrift-core.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthrifttyperep.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftannotation.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libserverdbginfo.a  /usr/lib64/libxxhash.so  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_server_async_tran.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_server.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_server_state.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_dsr_frontend.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_dsr_types.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_fizz_handshake.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_transport.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_buf_accessor.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_datagram_handler.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_batch_writer.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_cc_algo.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_codec_pktrebuilder.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_happyeyeballs.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_async_udp_socket.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_events.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_looper.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_observer.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_ack_handler.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_loss.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_pacing_functions.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_simple_frame_functions.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_functions.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_codec_pktbuilder.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_stream.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_flowcontrol.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_qlogger.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_stream_functions.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_machine.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_codec.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_handshake.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_codec_packet_number_cipher.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_codec_decode.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_codec_types.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_exception.a  /var/FBOSS/tmp_bld_dir/installed/fizz/lib/libfizz.a  /usr/lib64/libsodium.so  /usr/lib64/libz.so  /usr/lib64/librt.a  /var/FBOSS/tmp_bld_dir/installed/liboqs-1YXCy0qiTa4ku7OQ_N2qiBjN8Y5LfLjbAEwiIq6RfhI/lib64/liboqs.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_bufutil.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_transport_knobs.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_constants.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_transport_settings_functions.a  /var/FBOSS/tmp_bld_dir/installed/folly/lib/libfolly.a  /var/FBOSS/tmp_bld_dir/installed/fmt-uSYXU74IPh1alWrMBg51QsrvAsUtGQlguX0AigNHg-8/lib64/libfmt.a  /var/FBOSS/tmp_bld_dir/installed/glog--TiS8L7XT-dpPvonq2U7ueP0LLGtKprnfwIBV9cK38M/lib64/libglog.so  /var/FBOSS/tmp_bld_dir/installed/gflags-rTRHsBCNJ1QPFhXYI6Cn8x-wcYeGrQFSs0Z0lQGKwJ8/lib/libgflags.so.2.2.2  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_context.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_filesystem.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_atomic.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_program_options.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_regex.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_system.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_thread.a  /usr/lib64/libdouble-conversion.so  /usr/lib64/libevent.so  /usr/lib64/libz.so  /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  /usr/lib64/libbz2.so  /usr/lib64/liblzma.so  /usr/lib64/liblz4.so  /usr/lib64/libzstd.so  /usr/lib64/libsnappy.so  /usr/lib64/libdwarf.so  /usr/lib64/libiberty.a  /usr/lib64/libsodium.so  -ldl  /var/FBOSS/tmp_bld_dir/installed/libunwind-c63vwue81b-g1PVdgyfRrkAm8NgyayrkapvA8lMj46w/lib/libunwind.so  /usr/lib64/libre2.so && :
/usr/bin/ld: libsensor_service_utils.a(Utils.cpp.o): in function `facebook::fboss::platform::sensor_service::Utils::getConfig()':
Utils.cpp:(.text+0xbbe1): undefined reference to `vtable for facebook::fboss::platform::PlatformUtils'
/usr/bin/ld: Utils.cpp:(.text+0xbbeb): undefined reference to `facebook::fboss::platform::helpers::PlatformNameLib::PlatformNameLib(std::shared_ptr<facebook::fboss::platform::PlatformUtils>, std::shared_ptr<facebook::fboss::platform::PlatformFsUtils>)'
/usr/bin/ld: Utils.cpp:(.text+0xbbfd): undefined reference to `facebook::fboss::platform::helpers::PlatformNameLib::getPlatformName[abi:cxx11]() const'
/usr/bin/ld: Utils.cpp:(.text+0xbc3b): undefined reference to `vtable for facebook::fboss::platform::ConfigLib'
/usr/bin/ld: Utils.cpp:(.text+0xbc40): undefined reference to `facebook::fboss::platform::ConfigLib::getSensorServiceConfig(std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&) const'
/usr/bin/ld: Utils.cpp:(.text+0xbd6b): undefined reference to `facebook::fboss::platform::sensor_service::ConfigValidator::isValid(facebook::fboss::platform::sensor_config::SensorConfig const&)'
/usr/bin/ld: libsensor_service_utils.a(Utils.cpp.o): in function `std::shared_ptr<facebook::fboss::platform::PlatformFsUtils> std::make_shared<facebook::fboss::platform::PlatformFsUtils>()':
Utils.cpp:(.text._ZSt11make_sharedIN8facebook5fboss8platform15PlatformFsUtilsEJEESt10shared_ptrIT_EDpOT0_[_ZSt11make_sharedIN8facebook5fboss8platform15PlatformFsUtilsEJEESt10shared_ptrIT_EDpOT0_]+0x45): undefined reference to `facebook::fboss::platform::PlatformFsUtils::PlatformFsUtils(std::optional<std::filesystem::__cxx11::path> const&)'
/usr/bin/ld: libsensor_service_utils.a(Utils.cpp.o): in function `facebook::fboss::platform::helpers::PlatformNameLib::~PlatformNameLib()':
Utils.cpp:(.text._ZN8facebook5fboss8platform7helpers15PlatformNameLibD2Ev[_ZN8facebook5fboss8platform7helpers15PlatformNameLibD5Ev]+0xc): undefined reference to `vtable for facebook::fboss::platform::helpers::PlatformNameLib'
collect2: error: ld returned 1 exit status
```

Reviewed By: srikrishnagopu

Differential Revision: D64803322

fbshipit-source-id: 9185d812ee18061e8c4ebe95227381472e52c6be