Topology health check after every test
Summary:
We have seen cases where there are
scp.SCPException: Timout waiting for scp response
thrift.transport.TTransport.TTransportException: Socket read failed
thrift.transport.TTransport.TTransportException: socket error connecting to host
and testcases are failing. Suspision is that switch/hosts went to a bad state.
Changes in this diff include:
1. If there is a host in bad state , fail the system test run and dont run any testcases
2. Make sure switch and hosts are in good state after every test run

ToDo: Will do it in seperate diff
Make sure minimum hosts are available before starting a test case. some testcases need one testcase and some testcases work without even a single host(cmdline)

Reviewed By: capveg

Differential Revision: D7120706

fbshipit-source-id: 28ad8e0384dda323ed22de1313f16d1313526cce