Remove unused variable in order to fix OSS builds
Summary:
P1483796375

```
[1386/2202] Building CXX object CMakeFiles/hw_rx_slow_path_rate.dir/fboss/agent/hw/benchmarks/HwRxSlowPathBenchmark.cpp.o
FAILED: CMakeFiles/hw_rx_slow_path_rate.dir/fboss/agent/hw/benchmarks/HwRxSlowPathBenchmark.cpp.o
/usr/bin/c++ -DBOOST_ALL_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -I/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git -I/var/FBOSS/tmp_bld_dir/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-5sZB79UN9hjW9KUYwDVw8u6W6rANHi8ggOY1feNsZJs/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-Lt0bxC6rNoSR1M6bsW20fBL4hrR9P-Cwu_lSA8qohcQ/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-Lt0bxC6rNoSR1M6bsW20fBL4hrR9P-Cwu_lSA8qohcQ/experimental -I/usr/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-sV9xJRYiZaC4-CSCVo09Vn9IPgJiQXzbLUsnPFotZIY/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-kQKGKklc0aumA8if9sy9k6A7FCooRle8pTgxfgLlPro/include -I/var/FBOSS/tmp_bld_dir/installed/libyaml-2VMh27ArPh8aVyN5cfHNErIJlCuSeABaa-NqkPJJKnc/include -I/var/FBOSS/tmp_bld_dir/installed/exprtk-KyPSTqPDLkudutHqgNP7X4wdpL4WiJapiTIogE9xY2U -I/var/FBOSS/tmp_bld_dir/build/fboss -isystem /var/FBOSS/tmp_bld_dir/installed/folly/include -isystem /var/FBOSS/tmp_bld_dir/installed/fb303/include -isystem /var/FBOSS/tmp_bld_dir/installed/googletest-_IhrEQ1w-jHiRv3xGQ1to_IuTVLEJvdLCubRRZd0pus/include -isystem /var/FBOSS/tmp_bld_dir/installed/fmt-zW2UZzks_kkLgjMkCSVlHPSt2eK4xG2xik50GY_cEwM/include -isystem /usr/include/libdwarf -isystem /var/FBOSS/tmp_bld_dir/installed/fbthrift/include -isystem /var/FBOSS/tmp_bld_dir/installed/wangle/include -isystem /var/FBOSS/tmp_bld_dir/installed/fizz/include -isystem /var/FBOSS/tmp_bld_dir/installed/mvfst/include -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -fsized-deallocation -DENABLE_PATCH_APIS -std=gnu++20 -MD -MT CMakeFiles/hw_rx_slow_path_rate.dir/fboss/agent/hw/benchmarks/HwRxSlowPathBenchmark.cpp.o -MF CMakeFiles/hw_rx_slow_path_rate.dir/fboss/agent/hw/benchmarks/HwRxSlowPathBenchmark.cpp.o.d -o CMakeFiles/hw_rx_slow_path_rate.dir/fboss/agent/hw/benchmarks/HwRxSlowPathBenchmark.cpp.o -c /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/agent/hw/benchmarks/HwRxSlowPathBenchmark.cpp
/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/agent/hw/benchmarks/HwRxSlowPathBenchmark.cpp: In function ‘void facebook::fboss::RxSlowPathBenchmark()’:
/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/agent/hw/benchmarks/HwRxSlowPathBenchmark.cpp:41:17: error: unused variable ‘kEcmpWidth’ [-Werror=unused-variable]
   41 |   constexpr int kEcmpWidth = 1;
      |                 ^~~~~~~~~~
cc1plus: all warnings being treated as errors
[1393/2202] Building CXX object CMakeFiles/hw_anticipated_scale_route_add_speed.dir/fboss/agent/hw/benchmarks/HwAnticipatedScaleRouteAddBenchmark.cpp.o
ninja: build stopped: subcommand failed.
Command '['/usr/bin/cmake', '--build', '/var/FBOSS/tmp_bld_dir/build/fboss', '--target', 'install', '--config', 'RelWithDebInfo', '-j', '32']' returned non-zero exit status 1.
!! Failed
```

Building benchmarks in OSS fails due to treating the unused variable warning as an error.

Reviewed By: srikrishnagopu

Differential Revision: D59870076

fbshipit-source-id: e88edb7b8cddfd3c63d5be6431480a04348cf37e