Support SAI version 1.17.1 (#810)
Summary:
**Pre-submission checklist**
- [x] I've ran the linters locally and fixed lint errors related to the files I modified in this PR. You can install the linters by running `pip install -r requirements-dev.txt && pre-commit install`
- [x] `pre-commit run`

Description:
We tried to build FBOSS using NVIDIA SDK v4.8.3054 together with SAIBuild2511.34.1.52, where the SAI API version is 1.17.1. However, a compilation error occurred:

Error message:
build-helper.py: error: argument sai_version: invalid choice: '1.17.1' (choose from '1.13.2', '1.14.0', '1.15.0', '1.15.3', '1.16.0', '1.16.1', '1.16.3')

To resolve this, version 1.17.1 was added to the list of supported SAI versions in build-helper.py.

Pull Request resolved: https://github.com/facebook/fboss/pull/810

OK : 14
FAILED : 2
SKIPPED : 0
TIMEOUT : 0

There is the log file
[fboss_bins_nv_20260106_17_02_55_e9bb856e91_Switch_SDK_v4_8_3054_Release_SAIBuild2511_34_1_52_tar.tar.zst.zip](https://github.com/user-attachments/files/24630697/fboss_bins_nv_20260106_17_02_55_e9bb856e91_Switch_SDK_v4_8_3054_Release_SAIBuild2511_34_1_52_tar.tar.zst.zip)

Test Plan:
The Ensemble Link Test results are as follows.
Running all tests took 1:34:16.377938 between 2026-01-14 03:31:52.378063 and 2026-01-14 05:06:08.756001
[ OK ] warm_boot.AgentEnsembleOpticsTest.verifyTxRxLatches (311935 ms)
[ OK ] warm_boot.AgentEnsembleLinkTest.ecmpShrink (124139 ms)
[ OK ] warm_boot.AgentEnsembleLinkTest.asicLinkFlap (248892 ms)
[ OK ] warm_boot.AgentEnsembleLinkTest.getTransceivers (103877 ms)
[ OK ] warm_boot.AgentEnsembleLinkTest.trafficRxTx (91876 ms)
[ OK ] warm_boot.AgentEnsembleLinkTest.opticsTxDisableRandomPorts (173995 ms)
[ OK ] warm_boot.AgentEnsembleLinkTest.opticsTxDisableEnable (143883 ms)
[ OK ] warm_boot.AgentEnsembleLinkTest.qsfpColdbootAfterAgentUp (223943 ms)
[ OK ] warm_boot.AgentEnsembleLinkTest.iPhyInfoTest (128802 ms)
[ OK ] warm_boot.AgentEnsembleLinkTest.verifyIphyFecBerCounters (158935 ms)
[ OK ] warm_boot.AgentEnsembleLinkTest.clearIphyInterfaceCounters (116839 ms)
[ OK ] warm_boot.AgentEnsembleEmptyLinkTest.CheckInit (106813 ms)
[ FAILED ] cold_boot.AgentEnsembleLinkSanityTestDataPlaneFlood.warmbootIsHitLess (0 ms)
[ OK ] warm_boot.AgentEnsembleLinkSanityTestDataPlaneFlood.warmbootIsHitLess (98915 ms)
[ FAILED ] cold_boot.AgentEnsembleLinkSanityTestDataPlaneFlood.qsfpWarmbootIsHitLess (0 ms)
[ OK ] warm_boot.AgentEnsembleLinkSanityTestDataPlaneFlood.qsfpWarmbootIsHitLess (111892 ms)

Reviewed By: shiva-menta

Differential Revision: D93523682

Pulled By: joseph5wu

fbshipit-source-id: d9c9dcbad89a112a2f048941b8adb78d911f6fb5