Fix c++ cast warning
Summary:
Builds were failing due to this warning, explicitly cast to uint32t to avoid the warning.
```
buck build --flagfile fbcode//mode/opt fbcode//netos/services/fboss_qsfp_service:netos.service.fboss_qsfp_service--layer.debuginfo

Buck build failed for this target, and is likely caused by your changes.
Error message:
Action failed: fbcode//fboss/lib/phy:sai-phy-management-credo-0.7.2 (cfg:opt-linux-x86_64-fbcode-platform010-clang19-no-san#10b5d0c9c230ae61) (cxx_compile SaiPhyManager.cpp)
Remote command returned non-zero exit code 1
Remote action, reproduce with: `frecli cas download-action 8b37631309e10545beeb8b0813ea549bc8a0d88cc3983e4fdfe9c41035aa07dd:145`
Stdout: <empty>
Stderr:
fbcode/fboss/lib/phy/SaiPhyManager.cpp:959:51: error: non-constant-expression cannot be narrowed from type 'int' to 'ValueType' (aka 'unsigned int') in initializer list [-Wc++11-narrowing-const-reference]
  959 |         SaiPortTraits::Attributes::PrbsPolynomial{prbs.polynominal().value()});
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

```

Reviewed By: Protick666

Differential Revision: D77188861

fbshipit-source-id: d94fca63066854efac24a581846ce44fedcc1cf5