Add empty definition for `publishSwitchWatermarks`
Summary:
OSS Full build fails on IaC VM with the following error:

P1661869749
```
FAILED: sai_agent_hw_test-sai_impl
: && /usr/bin/c++ -DSAI_VERSION_11_0_EA_DNX_ODP -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -Wl,-wrap,sai_api_query -Wl,-wrap,sai_api_initialize -Wl,-wrap,sai_api_uninitialize -Wl,-wrap,sai_get_object_key CMakeFiles/sai_agent_hw_test-sai_impl.dir/fboss/agent/test/agent_hw_tests/SaiAgentHwTest.cpp.o -o sai_agent_hw_test-sai_impl  -Wl,-rpath,/var/FBOSS/tmp_bld_dir/installed/libyaml-_uopPZAyEuJ1pa5uqQsrLr4S97-mQpIjrUubZRQo2og/lib:/var/FBOSS/tmp_bld_dir/installed/gflags-rTRHsBCNJ1QPFhXYI6Cn8x-wcYeGrQFSs0Z0lQGKwJ8/lib:/var/FBOSS/tmp_bld_dir/installed/glog--TiS8L7XT-dpPvonq2U7ueP0LLGtKprnfwIBV9cK38M/lib64:  -Wl,--whole-archive  libagent_hw_test_src.a  /var/FBOSS/tmp_bld_dir/installed/sai_impl-QsIpM6gZa-bdzhWyVP78z_v9UeXMfUPkFd-FimYHKz0/lib/libsai_impl.a  libacl_test_utils.a  libcopp_test_utils.a  libsai_acl_utils.a  libsai_copp_utils.a  libhw_packet_utils.a  libolympic_qos_utils.a  libtraffic_policy_utils.a  libsai_traced_api.a  -Wl,--no-whole-archive  libagent_test_utils.a  liblabel_forwarding_utils.a  libhw_mock.a  libmulti_switch_hw_switch_handler.a  libaqm_test_utils.a  libport_stats_test_utils.a  libmulti_port_traffic_test_utils.a  libagent_hw_test.a  libagent_hw_test_constants.a  libmono_agent_ensemble.a  libmonolithic_agent_initializer.a  libsw_agent_initializer.a  libsetup_thrift.a  libagent_hw_test_thrift_handler.a  libsai_ecmp_utils.a  libproduction_features_cpp2.a  libstats_test_utils.a  libecmp_dataplane_test_util.a  libfabric_test_utils.a  libtrunk_utils.a  libpfc_test_utils.a  libqueue_test_utils.a  libinvariant_test_utils.a  libqos_test_utils.a  libvalidated_shell_commands_cpp2.a  libprod_config_factory.a  libdscp_marking_utils.a  libolympic_qos_utils.a  libqueue_per_host_test_utils.a  libcopp_test_utils.a  libtraffic_policy_utils.a  libagent_ensemble.a  libmain.a  libfboss_common_init.a  libagent_hw_test_ctrl_cpp2.a  libload_balancer_utils.a  libhw_pfc_utils.a  libroute_scale_gen.a  libroute_test_utils.a  libroute_distribution_gen.a  libload_balancer_test_utils.a  libl2learn_observer_util.a  libmac_test_utils.a  libsflow_shim_utils.a  libmirror_test_utils.a  libtrap_packet_utils.a  libvoq_test_utils.a  libecmp_helper.a  libdsf_config_utils.a  libhw_acl_utils.a  libhw_packet_utils.a  libpacket_snooper.a  libhw_switch_ensemble.a  libpkt_test_utils.a  libconfig_factory.a  libconfig_utils.a  libport_test_utils.a  libhwagent.a  libfboss_init.a  liblinkstate_toggler.a  libtest_ensemble_if.a  libhw_link_state_toggler.a  libmultiswitch_test_server.a  libsplit_agent_thrift_syncer.a  libmultiswitch_service.a  libsai_switch.a  libsai_platform.a  libthrift_handler.a  libdiag_shell.a  libsai_switch.a  libsai_platform.a  libthrift_handler.a  libdiag_shell.a  libhw_resource_stats_publisher.a  -Wl,--unresolved-symbols=ignore-all  libhw_trunk_counters.a  libhw_port_fb303_stats.a  libprbs_stats_entry.a  libsai_store.a  libref_map.a  -Wl,--unresolved-symbols=report-all  libwedge_led_utils.a  libfboss_i2c_lib.a  libi2c_controller_stats_cpp2.a  /usr/lib64/libusb-1.0.so  /usr/lib64/libcurl.so  libbcm_yaml_config.a  /var/FBOSS/tmp_bld_dir/installed/yaml-cpp-GUi5lTGEdkQXgMx9WRXIVQUXNp_t04zlqomCGse-Jq0/lib/libyaml-cpp.a  /var/FBOSS/tmp_bld_dir/installed/libyaml-_uopPZAyEuJ1pa5uqQsrLr4S97-mQpIjrUubZRQo2og/lib/libyaml.so  libled_structs_types_cpp2.a  libled_mapping_cpp2.a  libhandler.a  libpkt.a  liblog_thrift_call.a  libthrifthandler_utils.a  libsai_ctrl_cpp2.a  libsai_repl.a  libsai_api.a  libpython_repl.a  /usr/lib64/libpython3.9.so  -lutil  libhw_copp_utils.a  libresourcelibutil.a  libpacket_factory.a  /var/FBOSS/tmp_bld_dir/installed/googletest-GXS04svCG6RIq2z2VZ5_jAU0UT7-sdLvT-zqexiGLLs/lib64/libgmock_main.a  /var/FBOSS/tmp_bld_dir/installed/googletest-GXS04svCG6RIq2z2VZ5_jAU0UT7-sdLvT-zqexiGLLs/lib64/libgmock.a  /var/FBOSS/tmp_bld_dir/installed/googletest-GXS04svCG6RIq2z2VZ5_jAU0UT7-sdLvT-zqexiGLLs/lib64/libgtest.a  libhw_test_acl_utils.a  libacl_test_utils.a  libasic_test_utils.a  libcore.a  libmonolithic_switch_handler.a  libhw_switch_handler.a  libcapture.a  libpacket.a  libpktutil.a  libpacket_observer.a  libdiag_cmd_filter.a  libhw_cpu_fb303_stats.a  libhw_fb303_stats.a  libcounter_utils.a  liblldp.a  liblldp_structs_cpp2.a  librestart_time_tracker.a  libexponential_back_off.a  libphy_utils.a  libbidirectional_packet_stream.a  libasync_packet_transport.a  libpacket_stream_cpp2.a  /var/FBOSS/tmp_bld_dir/installed/iproute2-whtmrPlJs8hIRpwOqIyTUwmu8_LdyvkOl8DV_Z12tYY/lib/libnetlink.a  /usr/lib64/libnl-3.so  /usr/lib64/libnl-route-3.so  libthread_heartbeat.a  libhw_ctrl_cpp2.a  libloadbalancer_utils.a  libl2learn_event_observer.a  libagent_fsdb_sync_manager.a  libfsdb_syncer.a  libfsdb_pub_sub.a  libfsdb_stream_client.a  libcommon_thrift_utils.a  libthrift_service_client.a  libqsfp_cpp2.a  libfsdb_cpp2.a  libfsdb_flags.a  libcow_storage_mgr.a  libfboss_event_base.a  libphy_snapshot_manager.a  libsnapshot_manager.a  libalert_logger.a  libbuild_info_wrapper.a  libhw_switch.a  libhw_switch_fb303_stats.a  libstats.a  libcommon_utils.a  libmultiswitch_ctrl_cpp2.a  libplatform_base.a  libswitchinfo_utils.a  libroute_update_wrapper.a  libfib_updater.a  libhw_switch_warmboot_helper.a  libsw_switch_warmboot_helper.a  libhw_asic_table.a  libplatform_mapping_utils.a  libminipack_platform_mapping.a  libelbert_platform_mapping.a  libyamp_platform_mapping.a  libfake_test_platform_mapping.a  libfuji_platform_mapping.a  libgalaxy_platform_mapping.a  libwedge100_platform_mapping.a  libwedge40_platform_mapping.a  libwedge400_platform_utils.a  libwedge400c_platform_utils.a  libdarwin_platform_mapping.a  libwedge400_platform_mapping.a  libwedge400c_platform_mapping.a  libmorgan_platform_mapping.a  libcloud_ripper_platform_mapping.a  libmontblanc_platform_mapping.a  libtahan800bc_platform_mapping.a  libutils.a  libasic_utils.a  libswitch_asics.a  libversion_util.a  libswitchid_scope_resolver.a  libagent_dir_util.a  libload_agent_config.a  libmeru400biu_platform_mapping.a  libmeru400bia_platform_mapping.a  libmeru400bfu_platform_mapping.a  libmeru800bia_platform_mapping.a  libmeru800bfa_platform_mapping.a  libproduct_info.a  libjanga800bic_platform_mapping.a  libplatform_mapping.a  libstate.a  libfsdb_helper.a  libstate.a  libfsdb_helper.a  libhwswitch_matcher.a  liblacp_types.a  libfsdb_model.a  libfsdb_model_thriftpath_cpp2.a  libfsdb_model_cpp2.a  libagent_config_cpp2.a  libswitch_reachability_cpp2.a  libqsfp_state_cpp2.a  libqsfp_config_cpp2.a  libtransceiver_validation_cpp2.a  libqsfp_stats_cpp2.a  libsensor_service_stats_cpp2.a  libsensor_service_cpp2.a  libsensor_config_cpp2.a  libthriftpath_lib.a  libfsdb_utils.a  libcow_storage.a  libstorage.a  libfboss_config_utils.a  libexternal_phy.a  libagent_features.a  libstandalone_rib.a  libaddress_utils.a  libnetwork_to_route_map.a  libradix_tree.a  libstate_utils.a  libswitch_state_cpp2.a  liblabel_forwarding_action.a  liberror.a  libctrl_cpp2.a  libplatform_config_cpp2.a  libbcm_config_cpp2.a  libasic_config_cpp2.a  libasic_config_v2_cpp2.a  libagent_stats_cpp2.a  libhardware_stats_cpp2.a  libmka_structs_cpp2.a  libphy_cpp2.a  libio_stats_cpp2.a  libfb303_cpp2.a  liboptic_cpp2.a  libtransceiver_cpp2.a  liblink_cpp2.a  libprbs_cpp2.a  libproduct_info_cpp2.a  libthrift_cow_nodes.a  libnodebase.a  libthrift_cow_serializer.a  libthrift_cow_visitors.a  libfsdb_oper_cpp2.a  libfsdb_common_cpp2.a  libpatch_cpp2.a  /usr/lib64/libre2.so  libcow_visitor_results_cpp2.a  libcommon_file_utils.a  libsai_tracer.a  libasync_logger.a  /var/FBOSS/tmp_bld_dir/installed/fb303/lib/libfb303.a  /var/FBOSS/tmp_bld_dir/installed/fb303/lib/libfb303_thrift_cpp.a  libsai_version.a  libtuple_utils.a  libaddress_util.a  liblogging_util.a  libfboss_error.a  libfboss_types.a  libswitch_config_cpp2.a  libfboss_common_cpp2.a  libfboss_cpp2.a  libfunction_call_time_reporter.a  libhw_write_behavior.a  libcommon_cpp2.a  libnetwork_address_cpp2.a  libmpls_cpp2.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftcpp2.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftfrozen2.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftmetadata.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftanyrep.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthrifttype.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftprotocol.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftprotocol.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libasync.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libruntime.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libtransport.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/librpcmetadata.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libconcurrency.a  /lib64/libzstd.so  /var/FBOSS/tmp_bld_dir/installed/wangle/lib/libwangle.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthrift-core.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthrifttyperep.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libthriftannotation.a  /var/FBOSS/tmp_bld_dir/installed/fbthrift/lib/libserverdbginfo.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_server_async_tran.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_server.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_server_state.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_dsr_frontend.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_dsr_types.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_fizz_handshake.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_transport.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_buf_accessor.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_datagram_handler.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_batch_writer.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_cc_algo.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_codec_pktrebuilder.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_happyeyeballs.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_async_udp_socket.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_events.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_looper.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_observer.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_ack_handler.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_loss.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_pacing_functions.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_simple_frame_functions.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_functions.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_codec_pktbuilder.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_stream.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_flowcontrol.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_qlogger.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_stream_functions.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_state_machine.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_codec.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_handshake.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_codec_packet_number_cipher.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_codec_decode.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_codec_types.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_exception.a  /var/FBOSS/tmp_bld_dir/installed/fizz/lib/libfizz.a  /usr/lib64/libsodium.so  /usr/lib64/libz.so  /usr/lib64/librt.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_bufutil.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_transport_knobs.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_constants.a  /var/FBOSS/tmp_bld_dir/installed/mvfst/lib/libmvfst_transport_settings_functions.a  /var/FBOSS/tmp_bld_dir/installed/folly/lib/libfolly.a  /var/FBOSS/tmp_bld_dir/installed/fmt-uSYXU74IPh1alWrMBg51QsrvAsUtGQlguX0AigNHg-8/lib64/libfmt.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_context.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_filesystem.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_atomic.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_program_options.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_regex.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_system.a  /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/lib/libboost_thread.a  /usr/lib64/libdouble-conversion.so  /var/FBOSS/tmp_bld_dir/installed/gflags-rTRHsBCNJ1QPFhXYI6Cn8x-wcYeGrQFSs0Z0lQGKwJ8/lib/libgflags.so.2.2.2  /var/FBOSS/tmp_bld_dir/installed/glog--TiS8L7XT-dpPvonq2U7ueP0LLGtKprnfwIBV9cK38M/lib64/libglog.so  /usr/lib64/libevent.so  /usr/lib64/libz.so  /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  /usr/lib64/libbz2.so  /usr/lib64/liblzma.so  /usr/lib64/liblz4.so  /usr/lib64/libzstd.so  /usr/lib64/libsnappy.so  /usr/lib64/libdwarf.so  /usr/lib64/libiberty.a  /usr/lib64/libsodium.so  -ldl && :
/usr/bin/ld: libsai_switch.a(SaiSwitchManager.cpp.o): in function `facebook::fboss::SaiSwitchManager::updateStats(bool)':
SaiSwitchManager.cpp:(.text+0x6fcd): undefined reference to `facebook::fboss::publishSwitchWatermarks(facebook::fboss::HwSwitchWatermarkStats&)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Command '['/usr/bin/cmake', '--build', '/var/FBOSS/tmp_bld_dir/build/fboss', '--target', 'install', '--config', 'RelWithDebInfo', '-j', '32']' returned non-zero exit status 1.
!! Failed

real    2m11.786s
user    8m0.894s
sys     1m3.305s
```

This change adds an empty definition for this function, similar to [oss/SaiSwitchManager](https://www.internalfb.com/code/fbsource/[d1f74c8dd747037b10977e299e6baa9afb55b09c]/fbcode/fboss/agent/hw/sai/switch/oss/SaiSwitchManager.cpp), which cannot be included due to function definition conflicts between `oss/SaiSwitchManager.cpp` and `npu/bcm/SaiSwitchManager.cpp`.

Reviewed By: srikrishnagopu

Differential Revision: D64707842

fbshipit-source-id: c63c26215393eb217c447dc263d3b4a93509c2df