Fix OSS build failure due to missing thrift dep
Summary:
D60083159 added a dependency between `fboss/agent/if/hw_ctrl.thrift` and `fboss/agent/switch_state.thrift`.

This change adds that corresponding informtaion into the cmake files for the OSS builds.

Example error:

```
/usr/bin/ld: libhw_ctrl_cpp2.a(FbossHwCtrlAsyncClient.cpp.o): in function `apache::thrift::FutureCallback<facebook::fboss::state::SwitchState>::replyReceived(apache::thrift::ClientReceiveState&&)':
FbossHwCtrlAsyncClient.cpp:(.text._ZN6apache6thrift14FutureCallbackIN8facebook5fboss5state11SwitchStateEE13replyReceivedEONS0_18ClientReceiveStateE[_ZN6apache6thrift14FutureCallbackIN8facebook5fboss5state11SwitchStateEE13replyReceivedEONS0_18ClientReceiveStateE]+0x9b): undefined reference to `facebook::fboss::state::SwitchState::SwitchState()'
/usr/bin/ld: FbossHwCtrlAsyncClient.cpp:(.text._ZN6apache6thrift14FutureCallbackIN8facebook5fboss5state11SwitchStateEE13replyReceivedEONS0_18ClientReceiveStateE[_ZN6apache6thrift14FutureCallbackIN8facebook5fboss5state11SwitchStateEE13replyReceivedEONS0_18ClientReceiveStateE]+0xfd): undefined reference to `facebook::fboss::state::SwitchState::SwitchState(facebook::fboss::state::SwitchState&&)'
/usr/bin/ld: FbossHwCtrlAsyncClient.cpp:(.text._ZN6apache6thrift14FutureCallbackIN8facebook5fboss5state11SwitchStateEE13replyReceivedEONS0_18ClientReceiveStateE[_ZN6apache6thrift14FutureCallbackIN8facebook5fboss5state11SwitchStateEE13replyReceivedEONS0_18ClientReceiveStateE]+0x14a): undefined reference to `facebook::fboss::state::SwitchState::~SwitchState()'
/usr/bin/ld: FbossHwCtrlAsyncClient.cpp:(.text._ZN6apache6thrift14FutureCallbackIN8facebook5fboss5state11SwitchStateEE13replyReceivedEONS0_18ClientReceiveStateE[_ZN6apache6thrift14FutureCallbackIN8facebook5fboss5state11SwitchStateEE13replyReceivedEONS0_18ClientReceiveStateE]+0x17c): undefined reference to `facebook::fboss::state::SwitchState::~SwitchState()'
collect2: error: ld returned 1 exit status
[1108/1934] Building CXX object CMakeFiles/agent_test_utils.dir/fboss/agent/test/TestUtils.cpp.o
ninja: build stopped: subcommand failed.
Command '['/usr/bin/cmake', '--build', '/var/FBOSS/tmp_bld_dir/build/fboss', '--target', 'install', '--config', 'RelWithDebInfo', '-j', '32']' returned non-zero exit status 1.
!! Failed

```

Reviewed By: somasun

Differential Revision: D60293182

fbshipit-source-id: b64278de142db9b2c4e3c8275e79243180469b9f