Delete implicitly-deleted move ops in PlatformInfo
Summary:
When building qsfp with PAI SDK artifacts using clang, I noticed the following errors
```
In file included from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/lib/phy/SaiPhyManager.cpp:11:
/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/lib/phy/SaiPhyManager.h:170:5: error: explicitly defaulted move constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
  170 |     PlatformInfo(PlatformInfo&&) = default;
      |     ^
/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/lib/phy/SaiPhyManager.h:195:16: note: move constructor of 'PlatformInfo' is implicitly deleted because field 'updateMutex_' has a deleted move constructor
  195 |     std::mutex updateMutex_;
      |                ^
/opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_mutex.h:94:5: note: 'mutex' has been explicitly marked deleted here
   94 |     mutex(const mutex&) = delete;
      |     ^
/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/lib/phy/SaiPhyManager.h:170:36: note: replace 'default' with 'delete'
  170 |     PlatformInfo(PlatformInfo&&) = default;
      |                                    ^~~~~~~
      |                                    delete
/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/lib/phy/SaiPhyManager.h:171:19: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
  171 |     PlatformInfo& operator=(PlatformInfo&&) = default;
      |                   ^
/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/lib/phy/SaiPhyManager.h:195:16: note: move assignment operator of 'PlatformInfo' is implicitly deleted because field 'updateMutex_' has a deleted move assignment operator
  195 |     std::mutex updateMutex_;
      |                ^
/opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_mutex.h:95:12: note: 'operator=' has been explicitly marked deleted here
   95 |     mutex& operator=(const mutex&) = delete;
      |            ^
/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/lib/phy/SaiPhyManager.h:171:47: note: replace 'default' with 'delete'
  171 |     PlatformInfo& operator=(PlatformInfo&&) = default;
      |                                               ^~~~~~~
      |                                               delete
2 errors generated.
```

PlatformInfo declares move constructor and move assignment as `= default`,
but contains a `std::mutex` member (`updateMutex_`) and a
`folly::Synchronized` member which are both non-movable. This causes the
compiler to implicitly delete the defaulted move operations.

GCC silently handles this, but clang raises
`-Wdefaulted-function-deleted` (promoted to error via `-Werror`),
breaking OSS clang builds.

Move the declarations to private and explicitly mark them as `= delete`.
This is safe because PlatformInfo is stored as
`std::unique_ptr<PlatformInfo>` in the map, so move operations are
never called.

Reviewed By: AarjunC

Differential Revision: D97386062

fbshipit-source-id: f14ba12e4f1874ad592cd8be40f5b6a9704beb10