Fix failure with validateHighBufferValues test for native
Summary:
This test is currently failing for native, make it pass by lowering the shared
space allocation to stay within the bounds.

The test was failing with native SDK due to an attempted change of pool limit
and shared space. Looks like SDK has expectation on how these should be
changed, the assumption is, pool_total size - delta <= shared size, where
delta is the difference between old and new pool limits, throwing the error:

```
Error: Cannot increase pool limit morethan available shared space. Shared
space: 29345128 Sum of pool limits: 27079448, delta: -3157728
```

rohitpuri Going by the comment for the test, it states that higher value than
what was programmed earlier should be allowed, which holds with the value
programmed, however, not sure if there is any other assumption w.r.t. the value
being the MAX possible value for these params, in which case, this might need
more fine tuning.

Reviewed By: zechengh09

Differential Revision: D44774405

fbshipit-source-id: 2ef0bfa5a921695a6b8e5356b4dd7a9b5cacfdda