include "this" in implicit lambda capture in thrift handler
Summary:
As titled, include "this" in implicit lambda capture in thrift handler

This is towards enabling co-routines on FBOSS OSS + moving to C++20 + building sw and hw agent in OSS

Error seen:
```
 error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20
```

Reviewed By: shri-khare

Differential Revision: D50465461

fbshipit-source-id: 2a9538d65b791f88fdb68e7903d7997eb8e60635