Fix build error for Sai Replayer for fake sai implementation
Summary:
Original commit of building SAI Replayer log files D22511615 (https://github.com/facebook/fboss/commit/005881756d85c760e8302ebb1f80bef99821dfc3)
After the commit is landed, build issue was found on Sai Replayer with fake sai implementation T70223351

Instead of creating separate library for main function, directly compile the binary would solve the issue of undefined reference to sai_api_initialized()

Reviewed By: phshaikh

Differential Revision: D22619430

fbshipit-source-id: 4efa4b6fc5cb40e523e3c40bbf8e074ae1ec1098