Build failures
Summary:
- Changes in D92867199, D92867200 and D92785578 reference internal libs causing OSS build failures.

**Errors:-**

```bash
[1130/1911] Building CXX object CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp.o
FAILED: CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp.o
sccache /usr/bin/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -I/var/FBOSS/fboss -I/var/FBOSS/tmp_bld_dir/installed/fb303/include -I/var/FBOSS/tmp_bld_di r/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-necchMzYskb2vI3Fy1lXPZYHsEaDHA3d5aKFJuaX8js/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-BtwHe1dQCngVCkIiHkLFw9ZTbCbD5U3c9WlWAJVFR00/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-BtwHe1dQCngVCk IiHkLFw9ZTbCbD5U3c9WlWAJVFR00/experimental -I/usr/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-4-7j8MySbrB6b7_Thzq8WePjoVDLdw1YF6rpWbu9h4k/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-9DIVfqLql1GXHIOQsuMLH8xhjl1c5MVvUyrgBIJZyNU/include -I/var/FBOSS /tmp_bld_dir/installed/libyaml-ZqE2fU7rLsEPR2fIj-19PmtBiDwhziSfNiOEYVZxmvo/include -I/var/FBOSS/tmp_bld_dir/installed/exprtk-esIiZTWgMU93VIfW1B5mQe2E6M9BI2lpsgJKI5VEP9c -I/var/FBOSS/tmp_bld_dir/installed/libgpiod-DBb88ZWMPyeRgimsPRw6jXD2uxWB4-ddIaXLmwo_2d8/include -I/v ar/FBOSS/tmp_bld_dir/installed/googletest-5c88wOWwtxP4X8G2CK3ZFoh8m18vofHzQ-WrpjUKP5Q/include -I/var/FBOSS/tmp_bld_dir/build/fboss -isystem /var/FBOSS/tmp_bld_dir/installed/gflags-yCt6YKtSyVxb7s5yWeFBRPTeIDQPXvW01GWYjsWorow/include -isystem /var/FBOSS/tmp_bld_dir/insta lled/glog-a2J9hpAbudlvTKqAp9BtDzTUV_yFJzzjxoisbR7SSOA/include -isystem /var/FBOSS/tmp_bld_dir/installed/folly/include -isystem /var/FBOSS/tmp_bld_dir/installed/boost-P5mlHYbxWoxTLJDQACVGsMJkqx0bSlBfKe9vk26lGDw/include -isystem /var/FBOSS/tmp_bld_dir/installed/CLI11-_bf SoM8BNIuCL4ezbQtzfzdeMfr1brnU2jys8gxIFt4/include -isystem /var/FBOSS/tmp_bld_dir/installed/tabulate-EBOH5TkcjkifbZdOVtHSjzCRYacUh7kmoaX9MEKtMmw/include -isystem /var/FBOSS/tmp_bld_dir/installed/fmt-F0GUNLEpOf0DWem-8v1_jJNSY0OJfSn5BLYDZxh85Nc/include -isystem /var/FBOSS /tmp_bld_dir/installed/fast_float-da2ZPPhiPXk8Jp7edgMqCvFyiRnbXpQif5h3mCJJ-NE/include -isystem /usr/include/libdwarf-0 -isystem /var/FBOSS/tmp_bld_dir/installed/fbthrift/include -isystem /var/FBOSS/tmp_bld_dir/installed/wangle/include -isystem /var/FBOSS/tmp_bld_dir/in stalled/fizz/include -isystem /var/FBOSS/tmp_bld_dir/installed/mvfst/include -Wall -Werror -Wno-sign-compare -Wunused-variable -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -std=gnu++20 -fsized-deallocation -ftemplate-backtrace-limit=0 -MD -MT CMak eFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp.o -MF CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp.o.d -o CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp.o -c /var/FBOSS/fboss/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp
In file included from 11:
14:10: fatal error: fboss No such file or directory 14 | #include "fboss/cli/fboss2/commands/show/hardware/gen-cpp2/model_types.h"
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

```
[359/778] Building CXX object CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp.o
FAILED: CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp.o
sccache /usr/bin/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -I/var/FBOSS/fboss -I/var/FBOSS/tmp_bld_dir/installed/fb303/include -I/var/FBOSS/tmp_bld_di
r/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-necchMzYskb2vI3Fy1lXPZYHsEaDHA3d5aKFJuaX8js/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-BtwHe1dQCngVCkIiHkLFw9ZTbCbD5U3c9WlWAJVFR00/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-BtwHe1dQCngVCkIiHkLFw9ZTbCbD5U3c9WlWAJVFR00/experimental -I/usr/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-4-7j8MySbrB6b7_Thzq8WePjoVDLdw1YF6rpWbu9h4k/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-9DIVfqLql1GXHIOQsuMLH8xhjl1c5MVvUyrgBIJZyNU/include -I/var/FBOSS/tmp_bld_dir/installed/libyaml-ZqE2fU7rLsEPR2fIj-19PmtBiDwhziSfNiOEYVZxmvo/include -I/var/FBOSS/tmp_bld_dir/installed/exprtk-esIiZTWgMU93VIfW1B5mQe2E6M9BI2lpsgJKI5VEP9c -I/var/FBOSS/tmp_bld_dir/installed/libgpiod-DBb88ZWMPyeRgimsPRw6jXD2uxWB4-ddIaXLmwo_2d8/include -I/var/FBOSS/tmp_bld_dir/installed/googletest-5c88wOWwtxP4X8G2CK3ZFoh8m18vofHzQ-WrpjUKP5Q/include -I/var/FBOSS/tmp_bld_dir/build/fboss -isystem /var/FBOSS/tmp_bld_dir/installed/gflags-yCt6YKtSyVxb7s5yWeFBRPTeIDQPXvW01GWYjsWorow/include -isystem /var/FBOSS/tmp_bld_dir/installed/glog-a2J9hpAbudlvTKqAp9BtDzTUV_yFJzzjxoisbR7SSOA/include -isystem /var/FBOSS/tmp_bld_dir/installed/folly/include -isystem /var/FBOSS/tmp_bld_dir/installed/boost-P5mlHYbxWoxTLJDQACVGsMJkqx0bSlBfKe9vk26lGDw/include -isystem /var/FBOSS/tmp_bld_dir/installed/CLI11-_bfSoM8BNIuCL4ezbQtzfzdeMfr1brnU2jys8gxIFt4/include -isystem /var/FBOSS/tmp_bld_dir/installed/tabulate-EBOH5TkcjkifbZdOVtHSjzCRYacUh7kmoaX9MEKtMmw/include -isystem /var/FBOSS/tmp_bld_dir/installed/fmt-F0GUNLEpOf0DWem-8v1_jJNSY0OJfSn5BLYDZxh85Nc/include -isystem /var/FBOSS/tmp_bld_dir/installed/fast_float-da2ZPPhiPXk8Jp7edgMqCvFyiRnbXpQif5h3mCJJ-NE/include -isystem /usr/include/libdwarf-0 -isystem /var/FBOSS/tmp_bld_dir/installed/fbthrift/include -isystem /var/FBOSS/tmp_bld_dir/installed/wangle/include -isystem /var/FBOSS/tmp_bld_dir/installed/fizz/include -isystem /var/FBOSS/tmp_bld_dir/installed/mvfst/include -Wall -Werror -Wno-sign-compare -Wunused-variable -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -std=gnu++20 -fsized-deallocation -ftemplate-backtrace-limit=0 -MD -MT CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp.o -MF CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp.o.d -o CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp.o -c /var/FBOSS/fboss/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp
/var/FBOSS/fboss/fboss/cli/fboss2/commands/show/hardware/CmdShowHardware.cpp:16:10: fatal error: neteng/fboss/bgp/if/gen-cpp2/TBgpService.h: No such file or directory
   16 | #include "neteng/fboss/bgp/if/gen-cpp2/TBgpService.h"
      |
```

```
[1/405] Building CXX object CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/route/CmdShowRouteDetails.cpp.o
FAILED: CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/route/CmdShowRouteDetails.cpp.o
sccache /usr/bin/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -I/var/FBOSS/fboss -I/var/FBOSS/tmp_bld_dir/installed/fb303/include -I/var/FBOSS/tmp_bld_di
r/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-necchMzYskb2vI3Fy1lXPZYHsEaDHA3d5aKFJuaX8js/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-BtwHe1dQCngVCkIiHkLFw9ZTbCbD5U3c9WlWAJVFR00/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-BtwHe1dQCngVCk
IiHkLFw9ZTbCbD5U3c9WlWAJVFR00/experimental -I/usr/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-4-7j8MySbrB6b7_Thzq8WePjoVDLdw1YF6rpWbu9h4k/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-9DIVfqLql1GXHIOQsuMLH8xhjl1c5MVvUyrgBIJZyNU/include -I/var/FBOSS
/tmp_bld_dir/installed/libyaml-ZqE2fU7rLsEPR2fIj-19PmtBiDwhziSfNiOEYVZxmvo/include -I/var/FBOSS/tmp_bld_dir/installed/exprtk-esIiZTWgMU93VIfW1B5mQe2E6M9BI2lpsgJKI5VEP9c -I/var/FBOSS/tmp_bld_dir/installed/libgpiod-DBb88ZWMPyeRgimsPRw6jXD2uxWB4-ddIaXLmwo_2d8/include -I/v
ar/FBOSS/tmp_bld_dir/installed/googletest-5c88wOWwtxP4X8G2CK3ZFoh8m18vofHzQ-WrpjUKP5Q/include -I/var/FBOSS/tmp_bld_dir/build/fboss -isystem /var/FBOSS/tmp_bld_dir/installed/gflags-yCt6YKtSyVxb7s5yWeFBRPTeIDQPXvW01GWYjsWorow/include -isystem /var/FBOSS/tmp_bld_dir/insta
lled/glog-a2J9hpAbudlvTKqAp9BtDzTUV_yFJzzjxoisbR7SSOA/include -isystem /var/FBOSS/tmp_bld_dir/installed/folly/include -isystem /var/FBOSS/tmp_bld_dir/installed/boost-P5mlHYbxWoxTLJDQACVGsMJkqx0bSlBfKe9vk26lGDw/include -isystem /var/FBOSS/tmp_bld_dir/installed/CLI11-_bf
SoM8BNIuCL4ezbQtzfzdeMfr1brnU2jys8gxIFt4/include -isystem /var/FBOSS/tmp_bld_dir/installed/tabulate-EBOH5TkcjkifbZdOVtHSjzCRYacUh7kmoaX9MEKtMmw/include -isystem /var/FBOSS/tmp_bld_dir/installed/fmt-F0GUNLEpOf0DWem-8v1_jJNSY0OJfSn5BLYDZxh85Nc/include -isystem /var/FBOSS
/tmp_bld_dir/installed/fast_float-da2ZPPhiPXk8Jp7edgMqCvFyiRnbXpQif5h3mCJJ-NE/include -isystem /usr/include/libdwarf-0 -isystem /var/FBOSS/tmp_bld_dir/installed/fbthrift/include -isystem /var/FBOSS/tmp_bld_dir/installed/wangle/include -isystem /var/FBOSS/tmp_bld_dir/in
stalled/fizz/include -isystem /var/FBOSS/tmp_bld_dir/installed/mvfst/include -Wall -Werror -Wno-sign-compare -Wunused-variable -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -std=gnu++20 -fsized-deallocation -ftemplate-backtrace-limit=0 -MD -MT CMak
eFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/route/CmdShowRouteDetails.cpp.o -MF CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/route/CmdShowRouteDetails.cpp.o.d -o CMakeFiles/fboss2_lib.dir/fboss/cli/fboss2/commands/show/route/CmdShowRouteDetails.cpp
.o -c /var/FBOSS/fboss/fboss/cli/fboss2/commands/show/route/CmdShowRouteDetails.cpp
/var/FBOSS/fboss/fboss/cli/fboss2/commands/show/route/CmdShowRouteDetails.cpp:13:10: fatal error: common/network/AddressUtil.h: No such file or directory
   13 | #include "common/network/AddressUtil.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
/var/FBOSS/fboss/fboss/cli/fboss2/utils/CmdUtils.cpp:15:10: fatal error: neteng/netwhoami/lib/cpp/Recover.h: No such file or directory
   15 | #include "neteng/netwhoami/lib/cpp/Recover.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Reviewed By: shri-khare

Differential Revision: D93043249

fbshipit-source-id: a68c7f66ac7fcc5515e37438bf3d807dd33f780a