Fix `fboss_platform_services` build error due to unspecified dependency
Summary:
https://internalfb.com/sandcastle/workflow/3026418949596065825/artifact/actionlog.3026418949655484254.stdout.1?selectedLines=999-999-92-117

```
FAILED: CMakeFiles/state_utils.dir/fboss/agent/state/StateUtils.cpp.o
/bin/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -DIS_OSS_CPP17=true -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fb303/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fatal -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/nlohmann-json-AA3XJJsULRCLk6Clq0kF35PyAyFTdChpo4K5FhU5kXw/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/libsai-iOGKRnIDDiaQFgzHWRc72JXrcowbER2KJx9_B4rPXFo/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/libsai-iOGKRnIDDiaQFgzHWRc72JXrcowbER2KJx9_B4rPXFo/experimental -I/usr/include/libnl3 -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/iproute2-u4AgjJtte4UDdAcpggCKUq_uxWRaeYxTUZFJAvPNIMc/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/yaml-cpp-S7oxEW_LjdQ3Vr4Uux_EX6WdijLe8vX8urR7zUPM3wU/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/libyaml-LmnRHpBlRX5hf6pN0JY9ACzd3uN6jT8YUUi4qKNeSqE/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/exprtk-rBjT1-EkMHnvFh-8k4u0vs4GXXVSzNC6_wjaLvlJqeo -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/googletest-i8rYllf12uJfWbw0H1n4Ux3G_U_GyZlqpiSXenkHkWg/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build/fboss -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/gflags-g5RV5ObZF9J_vnk-F5KiX0wwA2Mm8poJ0t8rLCB-EY0/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/glog-h09Fede_TtgxU-_tk9qiTvb9kvFBDvQaUDRn7wXZisg/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/folly/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/boost-ig8PKAbG32vOsOONpYb_25RF1WTE30wVU5WDnIXYrjI/include -isystem /usr/include/libdwarf-0 -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-HlIOPJoxBVbJ6EvKc8NuB9HczFZ5UhKVbcnIxhrJgqs/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/wangle/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fizz/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/include -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -std=gnu++20 -fsized-deallocation -MD -MT CMakeFiles/state_utils.dir/fboss/agent/state/StateUtils.cpp.o -MF CMakeFiles/state_utils.dir/fboss/agent/state/StateUtils.cpp.o.d -o CMakeFiles/state_utils.dir/fboss/agent/state/StateUtils.cpp.o -c /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/state/StateUtils.cpp
In file included from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/thrift_cow/nodes/Types.h:131,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/state/Thrifty.h:25,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/state/RouteTypes.h:19,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/state/RouteNextHopEntry.h:19,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/state/MatchAction.h:18,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/state/AclEntry.h:14,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/state/AclMap.h:13,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/state/SwitchState.h:21,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/state/StateUtils.cpp:13:
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/thrift_cow/nodes/ThriftPrimitiveNode-inl.h:19:10: fatal error: fboss/fsdb/if/gen-cpp2/fsdb_oper_types.h: No such file or directory
   19 | #include "fboss/fsdb/if/gen-cpp2/fsdb_oper_types.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Reviewed By: peygar

Differential Revision: D58210325

fbshipit-source-id: 4b3676a8ce86e7adedfb0705606f9256345a34f3