Fix the openssl installation conflict issues in FBOSS build docker
Summary:
Recently I notice the following error when running fboss build docker:
```
STEP 16/20: RUN dnf install openssl* -y
Last metadata expiration check: 0:05:15 ago on Wed Jul 23 19:34:49 2025.
Package openssl-1:3.5.1-2.el9.x86_64 is already installed.
Package openssl-devel-1:3.5.1-2.el9.x86_64 is already installed.
Package openssl-libs-1:3.5.1-2.el9.x86_64 is already installed.
Error:
 Problem: problem with installed package fips-provider-next-1.2.0-2.el9.x86_64
  - package fips-provider-next-1.2.0-2.el9.x86_64 from System conflicts with openssl-fips-provider provided by openssl-fips-provider-1:3.5.1-2.el9.x86_64 from baseos
  - package fips-provider-next-1.2.0-2.el9.x86_64 from appstream conflicts with openssl-fips-provider provided by openssl-fips-provider-1:3.5.1-2.el9.x86_64 from baseos
  - cannot install the best candidate for the job
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Error: building at STEP "RUN dnf install openssl* -y": while running runtime: exit status 1
```

As the error log said, this `dnf install openssl*` is a bit too relaxing to include `openssl-fips-provider` which conflicts with CentOS9 base `fips-provider`
Removing this `dnf install openssl*` step since we already explicitly install `openssl openssl-devel openssl-libs`
before `getdeps.py install-system-deps`

If in the future, we need to install fips-provider, we could figure out how to solve the conflict later.
Right now, let's don't install everything with openssl prefix unless they're needed

Reviewed By: srikrishnagopu

Differential Revision: D78834851

fbshipit-source-id: 0d5b56cb448d76e968af7432d87cb7c2472d74df