Fix missing cmake dependency
Summary:
Fix the following linker error:

```
/usr/bin/ld: libhw_switch_test.a(HwTest.cpp.o): in function `facebook::fboss::HwTest::SetUp()':
HwTest.cpp:(.text+0xb93): undefined reference to `facebook::fboss::createHwEnsemble(std::set<facebook::fboss::HwSwitchEnsemble::Feature, std::less<facebook::fboss::HwSwitchEnsemble::Feature>, std::allocator<facebook::fboss::HwSwitchEnsemble::Feature> > const&)'
```

`createHwEnsemble` is defined in [HwSwitchEnsembleFactory.cpp](https://www.internalfb.com/code/fbsource/fbcode/fboss/agent/hw/sai/hw_test/HwSwitchEnsembleFactory.cpp) which is part of the [sai_switch_ensemble](https://www.internalfb.com/code/fbsource/[ac39c6df0011]/fbcode/fboss/github/cmake/AgentHwSaiHwTest.cmake?lines=22) target.

Reviewed By: paulcruz74

Differential Revision: D62053547

fbshipit-source-id: 00e876e182746cd176b3fb8401e74acfedb5b4e5