Fix build error on pci_device_check_test target
Summary:
Noticed the following error when building FBOSS full stack:
```
[43/3187] Linking CXX static library libsflow_structs.a
[44/3187] Building CXX object CMakeFiles/firmware_storage.dir/fboss/lib/firmware_storage/FbossFirmware.cpp.o
[45/3187] Building CXX object CMakeFiles/pci_device_check_test.dir/fboss/platform/platform_checks/tests/PciDeviceCheckTest.cpp.o
FAILED: CMakeFiles/pci_device_check_test.dir/fboss/platform/platform_checks/tests/PciDeviceCheckTest.cpp.o
/opt/rh/gcc-toolset-12/root/usr/bin/c++ -DIS_OSS=true -DIS_OSS_BRCM_SAI=true -I/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git -I/var/FBOSS/tmp_bld_dir/installed/gflags-Xf9DMhzYv1TptCg5oUrY1gAt5_v8yE1u1Y4XGY4Ueak/include -I/var/FBOSS/tmp_bld_dir/installed/glog-EDjm2qK7zlVfmb2mL8njHRbLhwO9Y41fpFzqU5wG1TQ/include -I/var/FBOSS/tmp_bld_dir/installed/folly/include -I/var/FBOSS/tmp_bld_dir/installed/boost-yPW7svNze8lcNPfinAa3VU5uaByk7s_aS0pCbiRbR1I/include -I/var/FBO
SS/tmp_bld_dir/installed/fb303/include -I/var/FBOSS/tmp_bld_dir/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-Kg-2xT-gNrc2cSdLOTNFVVWru0An4l2b8qYjk477fE4/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-F45UEaUxl0AtrHLNMde1vw-ecPBiNGOGPX6eEEN77hY/include -I/var/FBOSS/tmp_bld_dir/installed/sai_impl-GGFTEmzlqbYNEqYb_mOYSigMuB-l_jZa7qWvbObKnFE/include -I/usr/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-Q5zzc2RQRj59kRhx3KTJRk48v7umDlgAY0pBya8
6j3I/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-haFCmXqlA1saLIh6PD4alnwnBWtJnBimC9VjYVEDFW0/include -I/var/FBOSS/tmp_bld_dir/installed/libyaml-_9x8cxSboNoZY-ddORJtCPpurpu5oUYLxzfEjwEdFCc/include -I/var/FBOSS/tmp_bld_dir/installed/exprtk-ZxfD40_AoSCqr_jof1iXBe2Izq1HhlJWfnldT_NWss4 -I/var/FBOSS/tmp_bld_dir/installed/libgpiod-zTy3ddez5kWgtY9z370wPOSsx8f8FqwO06mlJvbsIm8/include -I/var/FBOSS/tmp_bld_dir/installed/sai_impl-GGFTEmzlqbYNEqYb_mOYSigMuB-l_jZa7qWvbObKnFE -i
system /var/FBOSS/tmp_bld_dir/installed/googletest-YpfIZIX53B0cH99_Jqvx8ROhmbEaxYaivD_VGqC1-eE/include -DSAI_VERSION_13_3_0_0_ODP -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -std=gnu++20 -MD -MT CMakeFiles/pci_device_check_test.dir/fboss/platform/platform_checks/tests/PciDeviceCheckTest.cpp.o -MF CMakeFiles/pci_device_check_test.dir/fboss/platform/platform_checks/tests/PciDeviceCheckTest.cpp.o.d -o CMakeFiles/pci_devi
ce_check_test.dir/fboss/platform/platform_checks/tests/PciDeviceCheckTest.cpp.o -c /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/platform/platform_checks/tests/PciDeviceCheckTest.cpp
Command '['/usr/bin/cmake', '--build', '/var/FBOSS/tmp_bld_dir/build/fboss', '--target', 'install', '--config', 'RelWithDebInfo', '-j', '16']' returned non-zero exit status 1.
!! Failed
In file included from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/platform/platform_checks/checks/PciDeviceCheck.h:19,
                 from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/platform/platform_checks/tests/PciDeviceCheckTest.cpp:11:
/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/platform/platform_checks/PlatformCheck.h:6:10: fatal error: fboss/platform/platform_checks/gen-cpp2/check_types_types.h: No such file or directory
    6 | #include "fboss/platform/platform_checks/gen-cpp2/check_types_types.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[46/3187] Building CXX object CMakeFiles/physical_memory.dir/fboss/lib/PhysicalMemory.cpp.o
```

D84279679 introduced the new pci device check but forgot to properly include the platform_checks library in the cmake
Besides either `pci_device_check` and `mock_platform_fs_utils` library doesn't exist. `mock_platform_fs_utils` is actually `platform_fs_utils` in OSS cmake

Reviewed By: birdsoup

Differential Revision: D85614260

fbshipit-source-id: ad48b7d96034af43c08c4b6dc490cc77933ad582