Fix missing CmdShowSdkDump.cpp in cmake
Summary:
As title. Saw this cpp is missing in cmake
```
undefined reference to `facebook::fboss::CmdShowQsfpSdkDump::queryClient(facebook::fboss::HostInfo const&)'
undefined reference to `facebook::fboss::CmdShowAgentSdkDump::queryClient[abi:cxx11](facebook::fboss::HostInfo const&)'
```

Reviewed By: somasun

Differential Revision: D93291117

fbshipit-source-id: 794b26bb6f7cd9148f970a1a2038048de365e8bb