Add dependency on switch_config to thriftpath_plugin (#279)
Summary:

GitHub actions started failing yesterday, example:

https://github.com/facebook/fboss/actions/runs/11441431604/job/31829463645

error:

```
2024-10-21T14:02:31.4673500Z FAILED: CMakeFiles/thriftpath_lib.dir/fboss/thriftpath_plugin/Path.cpp.o 
2024-10-21T14:02:36.2905287Z /usr/bin/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -I/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git -I/var/FBOSS/tmp_bld_dir/installed/fb303/include -I/var/FBOSS/tmp_bld_dir/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-U0LhNA07PbcS4T83XKOSZ3HYInJ3_tg5p07qL7_-vps/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-h_N5DoyuZgUV5t4C4mw8Wj9pRisSvsCQzjidPkan7LE/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-h_N5DoyuZgUV5t4C4mw8Wj9pRisSvsCQzjidPkan7LE/experimental -I/var/FBOSS/tmp_bld_dir/installed/libnl-cY4Ht8olcW_3VOgTg6qlw4QuZbhKuhlnURphXYMMaCE/include -I/var/FBOSS/tmp_bld_dir/installed/libnl-cY4Ht8olcW_3VOgTg6qlw4QuZbhKuhlnURphXYMMaCE/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-whtmrPlJs8hIRpwOqIyTUwmu8_LdyvkOl8DV_Z12tYY/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-JmcBkQPMe6Oji_ACuqIi3VtQy82ioJSsdyExsEGnA0A/include -I/var/FBOSS/tmp_bld_dir/installed/libyaml-QgUadIcbfNXGBhW-UuLzpyXbs1K0CaSnVc3tnUtlKp0/include -I/var/FBOSS/tmp_bld_dir/installed/libusb-nnnMCcsvBUmmVsIedpbpAPXAa51_dl4uPvosIUqX5j0/include -I/var/FBOSS/tmp_bld_dir/installed/libcurl-5ZobJ8cMV9f9HvIyrU7Y3FSaZztjF-_OtDVKDUCTDwg/include -I/var/FBOSS/tmp_bld_dir/installed/re2-DDmNFBNspRbbZLoi_O2gyt2Jn3jiTWIRrafL02YQBIM/include -I/var/FBOSS/tmp_bld_dir/installed/exprtk-HI3d9LHfz-zHyk7DhL_UIawNajHepWbxjg9SPq0do9c -I/var/FBOSS/tmp_bld_dir/installed/libgpiod-05CCWxy7mEgK9yrWn0RnEGecraYQzJsgtu0E00GKNzE/include -I/var/FBOSS/tmp_bld_dir/installed/googletest-HcwPZaMYp0ZH7G06dCfix-dfCi2cETPnWo5CghANi0o/include -I. -isystem /var/FBOSS/tmp_bld_dir/installed/gflags-pTGGX4P24fJ2Dl5y-C5XjPImd9-LwSRqWVfoIDfwMWM/include -isystem /var/FBOSS/tmp_bld_dir/installed/glog-yXkVEbeSSixwkk0GW8pE96Uf1_Oyb8-ZVTFuQcoBQTM/include -isystem /var/FBOSS/tmp_bld_dir/installed/folly/include -isystem /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/include -isystem /var/FBOSS/tmp_bld_dir/installed/fmt-E_U36VTl1xnwK5tbuHFt6MTwCsydAFfoV2cfkTBEN7w/include -isystem /var/FBOSS/tmp_bld_dir/installed/double-conversion-v9Mwzqp2jE6juC2CJGaP0rDOLK_dF2C7ypijlZG6xTY/include -isystem /var/FBOSS/tmp_bld_dir/installed/fast_float-w9lZJfzzyMFCgr5ESEBHrmGHR3tacOdrVGx1PZ_c8YQ/include -isystem /var/FBOSS/tmp_bld_dir/installed/libevent-umIaI7XtjrUfB_cJvTLEUdmWUao_qKxZh9m0b3lMP2A/include -isystem /var/FBOSS/tmp_bld_dir/installed/zlib-cmKMJT7qBc0eJpVHIP3aTP118xbrsRPwdh_A0BnPi5Y/include -isystem /var/FBOSS/tmp_bld_dir/installed/bz2-LwpkkllYvpJkKthvoCg1Hi1WnNGkG3aIdkUIp9blfEU/include -isystem /var/FBOSS/tmp_bld_dir/installed/xz-n-MAqk9F_9FgXlDGNzOsiT1AFGSrpAcP6unPtIm0xJ8/include -isystem /var/FBOSS/tmp_bld_dir/installed/lz4-ugAks3qwxIKb-uaIIfL9w-7iq7sjnlANYnPNhRx-bY0/include -isystem /var/FBOSS/tmp_bld_dir/installed/zstd-rHzICFvPRvqi1srrjH5JMdSKY9Oz3T3hDv1KQ7CdHIU/include -isystem /var/FBOSS/tmp_bld_dir/installed/snappy-LsciQV-JOAnxmRLmcDiwoH0mZL1ZyKbgE6ehX_JqMdI/include -isystem /var/FBOSS/tmp_bld_dir/installed/libdwarf-fj86SroWwyu_nbqwgj4NplHl-90U7s_pZmPsi5YvZW8/include -isystem /var/FBOSS/tmp_bld_dir/installed/libiberty-PN8sTVqdtj9eCY1Y3Tld7eDvHIt-crmlfIwgHcVEHBo/include/libiberty -isystem /var/FBOSS/tmp_bld_dir/installed/libsodium-TnbtfDok-sLNfJqgY4bFzvMTgmHimBjajAkElaQnqd8/include -isystem /var/FBOSS/tmp_bld_dir/installed/fbthrift/include -isystem /var/FBOSS/tmp_bld_dir/installed/wangle/include -isystem /var/FBOSS/tmp_bld_dir/installed/fizz/include -isystem /var/FBOSS/tmp_bld_dir/installed/mvfst/include -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -fsized-deallocation -std=gnu++2a -MD -MT CMakeFiles/thriftpath_lib.dir/fboss/thriftpath_plugin/Path.cpp.o -MF CMakeFiles/thriftpath_lib.dir/fboss/thriftpath_plugin/Path.cpp.o.d -o CMakeFiles/thriftpath_lib.dir/fboss/thriftpath_plugin/Path.cpp.o -c /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/thriftpath_plugin/Path.cpp
2024-10-21T14:02:36.2924425Z In file included from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/agent/state/NodeBase.h:12,
2024-10-21T14:02:36.2925486Z                  from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/agent/state/NodeBase-defs.h:12,
2024-10-21T14:02:36.2926548Z                  from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/thrift_cow/nodes/ThriftPrimitiveNode-inl.h:18,
2024-10-21T14:02:36.2927557Z                  from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/thrift_cow/nodes/Types.h:139,
2024-10-21T14:02:36.2928512Z                  from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/thrift_cow/storage/CowStorage.h:5,
2024-10-21T14:02:36.2929438Z                  from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/fsdb/common/Utils.h:5,
2024-10-21T14:02:36.2930331Z                  from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/thriftpath_plugin/Path.h:6,
2024-10-21T14:02:36.2931253Z                  from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/thriftpath_plugin/Path.cpp:3:
2024-10-21T14:02:36.2932523Z /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/agent/types.h:20:10: fatal error: fboss/agent/gen-cpp2/switch_config_types.h: No such file or directory
2024-10-21T14:02:36.2933533Z    20 | #include "fboss/agent/gen-cpp2/switch_config_types.h"
2024-10-21T14:02:36.2933957Z       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-10-21T14:02:36.2934305Z compilation terminated.
```

Differential Revision:
D64697595

Privacy Context Container: L1125642