Add cmis_cpp2 to qsfp_service
Summary:
Fix OSS build missing these files.

```
[654/702] Building CXX object CMakeFiles/qsfp_lib.dir/fboss/qsfp_service/platforms/wedge/WedgeQsfp.cpp.o
FAILED: CMakeFiles/qsfp_lib.dir/fboss/qsfp_service/platforms/wedge/WedgeQsfp.cpp.o
/opt/rh/gcc-toolset-12/root/usr/bin/g++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -I/var/FBOSS/fboss -I/var/FBOSS/tmp_bld_dir/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-cmDQNjiJPysD32-K5EYQEWDQB419kG8MIvqv9fsRYdQ/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-NsCzqfOofR1AnhHHbwqV46ajHxZgD1m_FKhRqD9uVng/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-NsCzqfOofR1AnhHHbwqV46ajHxZgD1m_FKhRqD9uVng/experimental -I/var/FBOSS/tmp_bld_dir/installed/libnl-UTplgFrNphBRPHNADFF3PTz6RGyLLY3r0DwWCzPc0nE/include -I/var/FBOSS/tmp_bld_dir/installed/libnl-UTplgFrNphBRPHNADFF3PTz6RGyLLY3r0DwWCzPc0nE/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-k3EjRS6jCDcH8tkpFFIxMlLmFggOJk_TFmrjGHokSC0/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-QRf08AAfsIjBOIJYpHf3mQNH-3BhiA_0v6tmE_2H0h0/include -I/var/FBOSS/tmp_bld_dir/installed/libyaml-Pz3KXp_g8unzbIb_n3pbqxzCguhi7LCqBhe3ocPHqYs/include -I/var/FBOSS/tmp_bld_dir/installed/libusb-Dxvy8GSATgobbWKPFfP0vSQMso0JuUtG8LiXc0YIi64/include -I/var/FBOSS/tmp_bld_dir/installed/libcurl-hCUqtqWZqMO5gNlxwDSBGClkmN7X6dIdGSNPXAg2PxE/include -I/var/FBOSS/tmp_bld_dir/installed/re2-GpE07UtYeSKDFolA1daMXnV8s6dnFOe4__lZvcLujyg/include -I/var/FBOSS/tmp_bld_dir/installed/exprtk-6qxcGRhBmgOXcbY1fnc3-gDWHF_lpIyNCdLwz-aaGao -I/var/FBOSS/tmp_bld_dir/installed/libgpiod-E9fCZfgRiFF5qWcWXnlYi3PYL43x-g6aakzlByYBgcI/include -I/var/FBOSS/tmp_bld_dir/installed/systemd-UtHeYxa3y4WOxdPBFU7wFa9NaLjSgZE5Av6JROKmdTE/include -I/var/FBOSS/tmp_bld_dir/installed/googletest-MHR5GVgH2T3SGEGAyFKJc6GKBjFckfjXW2UD66S25CE/include -I. -isystem /var/FBOSS/tmp_bld_dir/installed/gflags-t4E6m4gJoDM0mgiRhaeIz6lmYZFzT6w-fzgKsBeWtvU/include -isystem /var/FBOSS/tmp_bld_dir/installed/glog-NxxQlzlzBfUfCRZXTBLCDSRx3sCD0g6C60Oku9O9dxE/include -isystem /var/FBOSS/tmp_bld_dir/installed/folly/include -isystem /var/FBOSS/tmp_bld_dir/installed/boost-fycuet-5B-5_0oMZ_kPknJRLJZyy22sdy5K0QVGqBdc/include -isystem /var/FBOSS/tmp_bld_dir/installed/fb303/include -isystem /var/FBOSS/tmp_bld_dir/installed/xxhash-OMhBH-JMKXJk46cGi76656FVWNwHSFgaHQVTLUb5Ivo/include -isystem /var/FBOSS/tmp_bld_dir/installed/fmt-3KYIH9qO5qhn3wjMfngJ5th_Y3deVq7jDhM4AWu8h4M/include -isystem /var/FBOSS/tmp_bld_dir/installed/double-conversion-gpTmhlO8GOygiabeK1jrRJ-sfjhr5vU233fAL584a24/include -isystem /var/FBOSS/tmp_bld_dir/installed/fast_float-7KOY9Aj48YU6nmkixKQsFpZaG3C7RYdz7yqruV7R8nI/include -isystem /var/FBOSS/tmp_bld_dir/installed/libevent-bDnbxcATEwgMM8F1uupctEdtjlKM5IhbxrH87RY-rBE/include -isystem /var/FBOSS/tmp_bld_dir/installed/zlib-k7Ed77oUP72yMoNzO09TyVCZfi0ZAZzUASLQlGwSuTE/include -isystem /var/FBOSS/tmp_bld_dir/installed/bz2-sw7II_kt_P6zA1lGpOaVOio1fAye595vbT4GdrwYa84/include -isystem /var/FBOSS/tmp_bld_dir/installed/xz-5KxQ4eeiZ_ybHV5f4Jra78da1F6xwrvSk1Y6jPT7ofA/include -isystem /var/FBOSS/tmp_bld_dir/installed/lz4-KswzqyKxzZiGlebw4fiPDsZxk1VjsxgPowFxsBiRjm8/include -isystem /var/FBOSS/tmp_bld_dir/installed/zstd-1h0JXQb6fbitj5oqM_xWBGWy9uL71vutqxJYCA_e5nE/include -isystem /var/FBOSS/tmp_bld_dir/installed/snappy-McVxdEBIfTBa0iXtX9Hu4X4SCcA9q14Sr5IXDVJ3e88/include -isystem /var/FBOSS/tmp_bld_dir/installed/libdwarf-vo5-dVjBce_PKtvT2eRkEcjkuSQ3xYDD6CECBKwbdZs/include -isystem /var/FBOSS/tmp_bld_dir/installed/libiberty-2mwGXrQjEjD_ocnGRz9DSW-ilUugwjAMbNMiv5hNJS4/include/libiberty -isystem /var/FBOSS/tmp_bld_dir/installed/libsodium-eJHUMDZWXezhfG6DpUkWV8WlTTRUWmM77VVu60zNzdw/include -isystem /var/FBOSS/tmp_bld_dir/installed/fbthrift/include -isystem /var/FBOSS/tmp_bld_dir/installed/wangle/include -isystem /var/FBOSS/tmp_bld_dir/installed/fizz/include -isystem /var/FBOSS/tmp_bld_dir/installed/mvfst/include -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -fsized-deallocation -std=gnu++20 -MD -MT CMakeFiles/qsfp_lib.dir/fboss/qsfp_service/platforms/wedge/WedgeQsfp.cpp.o -MF CMakeFiles/qsfp_lib.dir/fboss/qsfp_service/platforms/wedge/WedgeQsfp.cpCommand '['/var/FBOSS/tmp_bld_dir/installed/cmake-HoOZ4SWMQXg7qzT1CQaU55GEZtkXpve0MB6m4Wf7LDA/bin/cmake', '--build', '/var/FBOSS/tmp_bld_dir/build/fboss', '--target', 'qsfp_lib', '--config', 'RelWithDebInfo', '-j', '32']' returned non-zero exit status 1.
!! Failed
p.o.d -o CMakeFiles/qsfp_lib.dir/fboss/qsfp_service/platforms/wedge/WedgeQsfp.cpp.o -c /var/FBOSS/fboss/fboss/qsfp_service/platforms/wedge/WedgeQsfp.cpp
/var/FBOSS/fboss/fboss/qsfp_service/platforms/wedge/WedgeQsfp.cpp:21:10: fatal error: fboss/qsfp_service/module/cmis/gen-cpp2/cmis_types.h: No such file or directory
   21 | #include "fboss/qsfp_service/module/cmis/gen-cpp2/cmis_types.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Reviewed By: joseph5wu

Differential Revision: D80542187

fbshipit-source-id: 16593643e2bafef551315e39f4d830a7e0fa0af5