Fix qsfp_service build failure
Summary:
D30746531 (https://github.com/facebook/fboss/commit/92ef2391b88c88d40a378496955b251c206238a6) introduced `module_state_machine` library in qsfp_service and had transceiver_manager include it.
But I forgot to add them to oss, which caused the following error:
```
undefined reference to `facebook::fboss::getModuleStateMachineEventName[abi:cxx11](facebook::fboss::ModuleStateMachineEvent)'
```

Reviewed By: jasmeetbagga, rajank7

Differential Revision: D31493898

fbshipit-source-id: 1864ceffb0b1827ffcb70be67fe4f2dcc1a85549