OSS Build fixes
Summary:
Fixed 2 errors

-
```
/data/users/hgulati/scratch/dataZusersZhgulatiZfbsource/fbcode_builder_getdeps/shipit/fboss/fboss/agent/test/link_tests/PtpTests.cpp:88: undefined reference to `facebook::fboss::HwTestPacketTrapEntry::~HwTestPacketTrapEntry()'
/data/users/hgulati/scratch/dataZusersZhgulatiZfbsource/fbcode_builder_getdeps/shipit/fboss/fboss/agent/test/link_tests/PtpTests.cpp:88: undefined reference to `facebook::fboss::HwTestPacketTrapEntry::~HwTestPacketTrapEntry()'
```

 - Unused variables in QsfpModule.cpp

There is still 1 more error left to be fixed
```
/data/users/hgulati/scratch/dataZusersZhgulatiZfbsource/fbcode_builder_getdeps/shipit/fboss/fboss/agent/test/link_tests/LinkSanityTests.cpp:146:35: error: ‘folly::Subprocess::Subprocess(const string&, const folly::Subprocess::Options&, const std::vector<std::__cxx11::basic_string<char> >*)’ is deprecated: Prefer no
t running in a shell or use `shellify`. [-Werror=deprecated-declarations]
```

Reviewed By: zechengh09

Differential Revision: D35572502

fbshipit-source-id: bf8ffb8b807ddb180ce3c435bee11d7ed83d96f5