Manually create a new stable commit tarball with a newer fb303 version
Summary:
When debugging the recent `conveyor_build_fboss_oss_agent` failed job:
https://www.internalfb.com/sandcastle/workflow/1923037040898369630
https://www.internalfb.com/sandcastle/workflow/1923037040898369630/artifact/actionlog.1923037041082549332.stdout.1?selectedLines=100866-100872-1-1
```
/opt/rh/gcc-toolset-12/root/usr/bin/g++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -I/var/FBOSS/fboss -I/var/FBOSS/tmp_bld_dir/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-BKAHPQs9qewPBb3JWtiR3H4hXRf1wVJ_zjhSmjHT2L4/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-NsCzqfOofR1AnhHHbwqV46ajHxZgD1m_FKhRqD9uVng/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-NsCzqfOofR1AnhHHbwqV46ajHxZgD1m_FKhRqD9uVng/experimental -I/usr/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-k3EjRS6jCDcH8tkpFFIxMlLmFggOJk_TFmrjGHokSC0/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-Bu24PX2lS0W4Ll4MJNWWfr6XOnlOMjqPv1c1UIk9T8s/include -I/var/FBOSS/tmp_bld_dir/installed/libyaml-cxUgJoi8NNG3ctyXyZCLBXx3kFbyS75xkjaiSS4fZl0/include -I/var/FBOSS/tmp_bld_dir/installed/exprtk-6qxcGRhBmgOXcbY1fnc3-gDWHF_lpIyNCdLwz-aaGao -I/var/FBOSS/tmp_bld_dir/installed/libgpiod-KLa7TQpN3l4NCI1VImJxI7oB3fm9VaVjN6szQKJD6k4/include -I/var/FBOSS/tmp_bld_dir/installed/googletest-Qva1sgckFYQmZ7OoSBDn2bJHSorjgcToZx0nnLhQ-xE/include -I/var/FBOSS/tmp_bld_dir/build/fboss -isystem /var/FBOSS/tmp_bld_dir/installed/gflags-BHEbaDqHQhJ3bReXNtUg-60gyywM1b0qpA0VboZEud4/include -isystem /var/FBOSS/tmp_bld_dir/installed/glog-hJwq_2nHTaP0M7249C6m_hAYv5LiRI0Mmn8rWBgDzTg/include -isystem /var/FBOSS/tmp_bld_dir/installed/folly/include -isystem /var/FBOSS/tmp_bld_dir/installed/boost-fycuet-5B-5_0oMZ_kPknJRLJZyy22sdy5K0QVGqBdc/include -isystem /var/FBOSS/tmp_bld_dir/installed/fb303/include -isystem /var/FBOSS/tmp_bld_dir/installed/fmt-9-QR8Ls5R769ldWXy_pwx5W85nLHNBJdZ8mBPleBQVU/include -isystem /var/FBOSS/tmp_bld_dir/installed/fast_float-Limz43H4XXzrZjwTkoQo8KsXI3JolmdDZkC6BBCW0Og/include -isystem /usr/include/libdwarf-0 -isystem /var/FBOSS/tmp_bld_dir/installed/fbthrift/include -isystem /var/FBOSS/tmp_bld_dir/installed/wangle/include -isystem /var/FBOSS/tmp_bld_dir/installed/fizz/include -isystem /var/FBOSS/tmp_bld_dir/installed/mvfst/include -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -std=gnu++20 -fsized-deallocation -ftemplate-backtrace-limit=0 -MD -MT CMakeFiles/core.dir/fboss/agent/SwSwitch.cpp.o -MF CMakeFiles/core.dir/fboss/agent/SwSwitch.cpp.o.d -o CMakeFiles/core.dir/fboss/agent/SwSwitch.cpp.o -c /var/FBOSS/fboss/fboss/agent/SwSwitch.cpp
/var/FBOSS/fboss/fboss/agent/SwSwitch.cpp: In member function ‘facebook::fboss::TeFlowStats facebook::fboss::SwSwitch::getTeFlowStats()’:
/var/FBOSS/fboss/fboss/agent/SwSwitch.cpp:1250:39: error: ‘using element_type = struct folly::Synchronized<facebook::fb303::MultiLevelTimeSeries<long int>, facebook::fb303::MutexWrapper>’ {aka ‘struct folly::Synchronized<facebook::fb303::MultiLevelTimeSeries<long int>, facebook::fb303::MutexWrapper>’} has no member named ‘wlock’; did you mean ‘lock’?
 1250 |         auto lockedStatPtr = statPtr->wlock();
      |                                       ^~~~~
      |                                       lock
```

D84917811 made a recent change last week to change all the stat pointer to use wlock() instead of lock().
But this need a newer version of fb303 (https://github.com/facebook/fb303/commit/8fda3bf58d1276848ebe9769563899fc26e43724)
However `conveyor_build_fboss_oss_agent` will only use the latest stable commit to fetch any fboss dependency(i.e. fb303 here)
If you scrolled up to the very beginning of the logs from the previous link, you can see:
```
+ cd /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fb303.git && \
+ git \
+      fetch \
+      origin \
+      8d345b356d8d0d99dfc90b74891e60583d389c31
From https://github.com/facebook/fb303
 * branch                8d345b356d8d0d99dfc90b74891e60583d389c31 -> FETCH_HEAD
```
the commit we used for folly stable commit is pretty old:
```
[joseph5wuadmin@snc-fbossossinfra25 fb303]$ git log --pretty=format:"%h%x09%an%x09%ad%x09%s" | grep 8d345b
8d345b356       Joseph Beshay   Tue Oct 7 13:58:14 2025 -0700   Do not use homebrew's boost
```

However because we only create a stable commit when each service node passed their build and tests, there's no way to auto create a newer version of the stable commit tarball.

NOTE: This is a hacky fix that I had to manually change the stable commit of fb303 dependency to a newer one; then create a new tarball.

The exact steps I did are:
```
$ cd ~/fbsource/fbcode/fboss/oss/stable_commits
$ tar -zxvf github_hashes_10142025_180537.tar.gz
$ vi build/deps/github_hashes/facebook/folly-rev.txt
// change the commit id from 8d345b356d8d0d99dfc90b74891e60583d389c31 to 5256cfad4f0d3ff0d99b11051a182746721595c7
$ tar -zcvf github_hashes_10202025_165100.tar.gz build
$ ./update_symlinks
$ rm -rf build
```

As for investigating why the stable commit of our dependencies are not properly updated, I created T242156260 and assigned to KevinYakar

Reviewed By: srikrishnagopu

Differential Revision: D85104180

fbshipit-source-id: e8372eb5500c0f94b39fc6aa5f84d4cf4477034f