Use gen-stable-commits-tarball.py to generate the new stable commit tarball to replace the one created manually
Summary:
My last diff is not using this script(gen-stable-commits-tarball.py) to generate the stable commits tarball but just manually changing the fb303 commit.
I suspected this messed up with the permission of the tarball which caused the `conveyor_build_fboss_oss_agent` failed when trying to unzip the tarball using  `twsvcscm` user
https://www.internalfb.com/sandcastle/workflow/3292131327618920009
```
tar: build/fbcode_builder/manifests/zstd: Cannot change ownership to uid 117797, gid 100: Invalid argument
tar: build/fbcode_builder/manifests: Cannot change ownership to uid 117797, gid 100: Invalid argument
tar: build/fbcode_builder: Cannot change ownership to uid 117797, gid 100: Invalid argument
tar: build: Cannot change ownership to uid 117797, gid 100: Invalid argument
tar: Exiting with failure status due to previous errors
Error: building at STEP "RUN tar xvzf fboss/oss/stable_commits/latest_stable_hashes.tar.gz": while running runtime: exit status 2
```

Unfortunately, we can't be able to catch this using iac-vm since we always use our admin account to access the vm and create the docker.
But in our job here, we're using `twsvcscm` which needs to be cautious to deal with the permission.

Therefore, this diff will use `gen-stable-commits-tarball.py` which is the same script that `fboss_oss_stable_commit_publisher` job uses to create the stable commits tarball
https://www.internalfb.com/sandcastle/job/22518000377846644

The exact steps I did:
```
$ cd fbcode
// Run the script twice in a short time to create two tarballs which has the same git commits for the dependencies
// Since both of the previous and latest tarballs are not working any more. I decided to replace both of them at the same time
$ python3 fboss/facebook/scripts/gen-stable-commits-tarball.py --opensource_dir "$( hg root )/fbcode/opensource" --out fboss/oss/stable_commits
$ python3 fboss/facebook/scripts/gen-stable-commits-tarball.py --opensource_dir "$( hg root )/fbcode/opensource" --out fboss/oss/stable_commits
// Update the symlinks so the two new tarballs can replace both previous and latest
$ ./fboss/oss/stable_commits/update_symlinks

❯❯❯ ls -al fboss/oss/stable_commits
total 49
drwxr-xr-x  7 joseph5wu users     0 Oct 21 12:58 .
drwxr-xr-x 19 joseph5wu users     0 Oct 20 13:57 ..
-rw-r--r--  1 joseph5wu users 23984 Oct 21 12:57 github_hashes_10212025_125705.tar.gz
-rw-r--r--  1 joseph5wu users 23924 Oct 21 12:57 github_hashes_10212025_125742.tar.gz
lrwxrwx---  1 joseph5wu users    36 Oct 21 12:58 latest_stable_hashes.tar.gz -> github_hashes_10212025_125742.tar.gz
lrwxrwx---  1 joseph5wu users    36 Oct 21 12:58 previous_stable_hashes.tar.gz -> github_hashes_10212025_125705.tar.gz
-rwxr-xr-x  1 joseph5wu users   387 Oct 20 13:57 update_symlinks
```

Reviewed By: huruinan

Differential Revision: D85178902

fbshipit-source-id: 8681c4d008a09c9bbb27b44e05cb7123b43d81d2