[Accton][MP3N] Support SAI version 1.17.1
Description:
We tried to build FBOSS using NVIDIA SDK v4.8.3054 together with SAIBuild2511.34.1.52, where the SAI API version is 1.17.1.
However, a compilation error occurred:

Error message:
build-helper.py: error: argument sai_version: invalid choice: '1.17.1'
(choose from '1.13.2', '1.14.0', '1.15.0', '1.15.3', '1.16.0', '1.16.1', '1.16.3')

To resolve this, version 1.17.1 was added to the list of supported SAI versions in build-helper.py.