Fix compilation issue when building fabric_test_util
Summary:
When building fboss agent hw test on OSS, I noticed the following issue:
```
[3/16] Building CXX object CMakeFiles/fabric_test_utils.dir/fboss/agent/test/utils/FabricTestUtils.cpp.o
FAILED: CMakeFiles/fabric_test_utils.dir/fboss/agent/test/utils/FabricTestUtils.cpp.o
/usr/bin/c++ -DBOOST_ALL_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -DIS_OSS_BRCM_SAI=true -I/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git -I/var/FBOSS/tmp_bld_dir/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-f9h6EjVN2UVxDVpnYDdkoEXKC7JjQ_cLlQHpsxPPyzk/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-d1VvV_8gewUgwVPsIx5-0N6jznxXl5vhm0Oy5Ck_59k/include -I/var/FBOSS/tmp_bld_dir/ins
talled/sai_impl-x4RZ8etboZg-LNwXvcuxGnuwSL8HumHwEdNNsZS9ojA/include -I/usr/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-nehCCz6gP2nFuumiKlAm0SeurYDgLIDWtk9lvFz5UIU/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-fONUqZcX0B0s8CjfwmoyrcHQgqnkIYmJDEEmDN7rt78/include -I/var/FBOSS/tmp_bld_dir/installed/libyaml-7yZK6ftxcmpoSvgAUIBevwhlnhrs4Fhrc_2gzdRFMhc/include -I/var/FBOSS/tmp_bld_dir/installed/ex
prtk-ENT5af3Zj7JYb-Q12ThFG71wBmxhUhArFMHjMVbj5NY -I/var/FBOSS/tmp_bld_dir/installed/libgpiod-5s_IscheOKKat38Cc1YZymF1VdyKpWjdt7mD2JQZa2k/include -I/var/FBOSS/tmp_bld_dir/installed/systemd-ZOgUNeoZaQluersMcDUlwxVIx384stA8OELbgl2cKwQ/include -I/var/FBOSS/tmp_bld_dir/installed/sai_impl-x4RZ8etboZg-LNwXvcuxGnuwSL8HumHwEdNNsZS9ojA -I/var/FBOSS/tmp_bld_dir/build/fboss -isystem /var/FBOSS/tmp_bld_dir/installed/folly/i
nclude -isystem /var/FBOSS/tmp_bld_dir/installed/fb303/include -isystem /var/FBOSS/tmp_bld_dir/installed/fmt-dMVFvNBUMZFogeR3u8ZXSzvDOmvNX4rNRAjhNUmtIOc/include -isystem /usr/include/libdwarf -isystem /var/FBOSS/tmp_bld_dir/installed/fbthrift/include -isystem /var/FBOSS/tmp_bld_dir/installed/wangle/include -isystem /var/FBOSS/tmp_bld_dir/installed/fizz/include -isystem /var/FBOSS/tmp_bld_dir/installed/mvfst/inc
lude -DSAI_VERSION_14_0_EA_ODP -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -fsized-deallocation -std=gnu++20 -MD -MT CMakeFiles/fabric_test_utils.dir/fboss/agent/test/utils/FabricTestUtils.cpp.o -MF CMakeFiles/fabric_test_utils.dir/fboss/agent/test/utils/FabricTestUtils.cpp.o.d -o CMakeFiles/fabric_test_utils.dir/fboss/agent/test/utils/FabricTestUtils.cpp.o
 -c /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/agent/test/utils/FabricTestUtils.cpp
In file included from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/agent/test/utils/FabricTestUtils.h:14,
                 from /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/agent/test/utils/FabricTestUtils.cpp:11:
/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/agent/test/AgentEnsemble.h:23:10: fatal error: fboss/agent/if/gen-cpp2/AgentHwTestCtrl.h: No such file or directory
   23 | #include "fboss/agent/if/gen-cpp2/AgentHwTestCtrl.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

We need to make sure to link `agent_ensemble` when include `AgentEnsemble.h`

Reviewed By: KevinYakar

Differential Revision: D80349954

fbshipit-source-id: 8f6be5be4fef63d2a041e23509f771d40257318d