Add a simple thrift_latency_test.cpp to verify oss thrift slowness issue
Summary:
This diff just added the experimental thrift_latency_test.cpp from https://github.com/facebook/folly/pull/2559

With the oss build, this simple thrift call can take 6418ms
```
[root@0eb3f90dd235 fboss]# ./thrift_latency_test
Creating Thrift server...
I0116 22:30:33.090906 42865 ThriftServer.cpp:2060] Using randomly generated TLS ticket keys.
I0116 22:30:33.091259 42865 ThriftServer.cpp:988] Using resource pools on address/port [::1]:0: thrift flag: true, enable gflag: false, disable gflag: false, runtime actions:
I0116 22:30:33.091567 42865 ThriftServer.cpp:1538] Resource pools configured: 2
I0116 22:30:33.092444 42865 ThriftServer.cpp:746] ThriftServer listening on address/port: [::1]:37999
Server listening on port 37999
Making RPC call...
RPC call completed in 6418 ms
Result: lastAppliedInMs = 12345
ERROR: RPC took too long! Expected < 100ms
```

While in our internal build, the same test without using any FBOSS internal logic only take 16ms
```
❯❯❯ buck2 run fbcode//fboss/cli/fboss2/test:thrift_latency_test
Buck UI: https://www.internalfb.com/buck2/fc447728-e42e-45da-8e9b-a29ae80abeb5
Network: Up: 0B  Down: 0B
Command: run.
Time elapsed: 0.0s
BUILD SUCCEEDED - starting your binary
Creating Thrift server...
I0116 14:35:48.140404 328824 ThriftServer.cpp:2060] Using randomly generated TLS ticket keys.
I0116 14:35:48.142755 328824 ThriftServer.cpp:988] Using resource pools on address/port [::1]:0: thrift flag: true, enable gflag: false, disable gflag: false, runtime actions:
I0116 14:35:48.145723 328824 ThriftServer.cpp:1538] Resource pools configured: 2
I0116 14:35:48.281738 328824 ThriftServer.cpp:746] ThriftServer listening on address/port: [::1]:40581
Server listening on port 40581
Making RPC call...
RPC call completed in 16 ms
Result: lastAppliedInMs = 12345
OK: RPC latency is acceptable
```

This is a huge difference b.w OSS build and internal build: **6418ms vs 16ms**
As you can see in thrift_latency_test.cpp, we used `ScopedServerInterfaceThread` to spawn a simple fboss agent thrift server, then use `FbossCtrlAsyncClient` with `RocketClientChannel` to call a thrift function.
No FBOSS internal logic is used here.

I am suspecting there's performance discrepancy b/w our internal build and OSS build for fbthrift.

Based on the new comments from https://fb.workplace.com/groups/560979627394613/permalink/3541014286057784/
I asked Metamate to generate a similar test but use EpollBackend and IoUring to create a thrift server

Reviewed By: kevin645

Differential Revision: D90894498

fbshipit-source-id: c8d04d6434c7aca326bc33133d40f514ea8252bb