Add missing setup_thrift_prod for sai_invariant_agent_test-sai_impl
Summary:
Fixed the following compiling issue on OSS:
```
[2944/3019] Linking CXX executable sai_invariant_agent_test-sai_impl
FAILED: sai_invariant_agent_test-sai_impl
...
/opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: libsw_agent_initializer.a(SwAgentInitializer.cpp.o): in function `facebook::fboss::SwAgentInitializer::initAgent(facebook::fboss::HwSwitchCallb
ack*, facebook::fboss::HwWriteBehavior const&)':
SwAgentInitializer.cpp:(.text+0x102a): undefined reference to `facebook::fboss::createThriftHandler(facebook::fboss::SwSwitch*)'
collect2: error: ld returned 1 exit status
```

Reviewed By: KevinYakar

Differential Revision: D82666912

fbshipit-source-id: 787726f269cf3e9eba7b940f14a27b8092ab3140