Add other_dependency RPM build example (#992)
Summary:
**Pre-submission checklist**
- [X] I've ran the linters locally and fixed lint errors related to the files I modified in this PR. You can install the linters by running `pip install -r requirements-dev.txt && pre-commit install`
- [X] `pre-commit run`

This example shows how to build an RPM to be used as an "other_dependency" in the manifest. It create an empty RPM which can be installed.

This also serves as a CI fixture to ensure that other_dependencies are build and installed correctly during an image build.

Pull Request resolved: https://github.com/facebook/fboss/pull/992

Test Plan:
This file is already referenced in from_source.json due to a merge error. See that the Distro Build GHA does not fail like in https://github.com/facebook/fboss/actions/runs/22879359535/job/66378473243?pr=991 with the error:
```
distro_cli.lib.exceptions.ComponentError: Build script not found: /home/runner/work/fboss/fboss/fboss-image/examples/thirdparty_build.sh (from manifest path: examples/thirdparty_build.sh)
```

The build will likely fail due to other missing fixes however.

Reviewed By: shiva-menta

Differential Revision: D95957313

Pulled By: kevin645

fbshipit-source-id: 6275964a6aeb540c5d2dc5e2ccc7100fa05021ff