type cast to avoid different enum arithmetic errors in dhcp packet handler
Summary:
As titled, type cast to avoid different enum arithmetic errors in dhcp packet handler

This is towards enabling co-routines on FBOSS OSS + moving to C++20 + building sw and hw agent in OSS

Error seen:
```
error: arithmetic between different enumeration types
```

Reviewed By: shri-khare

Differential Revision: D50465454

fbshipit-source-id: 697862e1e3c7d81e522c774f021da89753aabf1d