Fix macro conflict with glibc-2.40+ headers
Summary:
Newer versions of glibc define a `IP_PROTOCOL` macro in the inet headers
which leads to conflicts with this enum.  As there's not really a great way to
prevent this conflict from the glibc side, this just renames the variants in our
thrift struct.

```
buck-out/v2/gen/fbcode/2539d56e20c7e2e1/fboss/agent/__switch_config-cpp2-types__/buck-headers/fboss/agent/gen-cpp2/switch_config_types.h:2673:3: error: expected identifier
 2673 |   IP_PROTOCOL = 6,
      |   ^
fbcode/third-party-buck/platform010-aarch64/build/glibc/include/bits/in.h:132:23: note: expanded from macro 'IP_PROTOCOL'
  132 | #define IP_PROTOCOL                     52
      |                                         ^
1 error generated.
```

Reviewed By: jasmeetbagga

Differential Revision: D67050587

fbshipit-source-id: a4bdf7369d173f0a4c5f7d3e0c55bc15faeaec9c