include "this" in implicit lambda capture in ipv6handler
Summary:
As titled, include "this" in implicit lambda capture in ipv6handler

This is towards enabling co-routines on FBOSS OSS + moving to C++20 + building sw and hw agent in OSS

Error seen:
```
 error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20
```

Reviewed By: shri-khare

Differential Revision: D50465463

fbshipit-source-id: ede46aa2be662a720dcfe5f126d3ae9f4ffa5308