Fix setting maintap in zero preemphasis setting
Summary:
As titled. The goal is to set preemphasis + all six-tap values to zero (except main), and then set main to zero.

This is due to the check on yamp platform -
  ERROR: in BLACKHAWK, main TAP is expected to be greater than all other TAPs.ERROR:chip/blackhawk/tier1/blackhawk_tsc_config.c->blackhawk_tsc_validate_txfir_cfg() SerDes err_code = ERR_CODE_BAD_PTR_OR_INVALID_INPUT : 26

Fix this by first setting sixtap but keeping main the same, and then set main to zero.

Reviewed By: daiwei1983

Differential Revision: D58880165

fbshipit-source-id: 134ae9349879f67b3cdd80e1fb53fa853e58dc1d