include "this" in implicit lambda capture in sai switch
Summary:
As titled,  include "this" in implicit lambda capture in sai switch

This is towards enabling co-routines on FBOSS OSS + moving to C++20 + building sw and hw agent in OSS

Error seen:
```
 error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20
```

Reviewed By: shri-khare

Differential Revision: D50465456

fbshipit-source-id: e67c55bae0a3608dd94ee0ad4787b567ffb07f82