pin python version to 3.8 for OSS
Summary:
Pinning python version to 3.8 for OSS. This is towards building OSS in legolinux sandcastle.

With python version not pinned, legolinux ends up picking python3.10 from a different path (/usr/local/fbcode/platform010/lib
) causing linking issues.

Given that python manifest is already pointing to 3.8, lets pin the python version to 3.8

```
//usr/local/fbcode/platform010/lib/libresolv.so.2: undefined reference to `__libc_res_queriesmatch@GLIBC_PRIVATE'
/usr/local/fbcode/platform010/lib/libpython3.10.so: undefined reference to `pthread_kill@GLIBC_2.34'
//usr/local/fbcode/platform010/lib/libkrb5.so.3: undefined reference to `ns_name_uncompress@GLIBC_2.34'
/usr/local/fbcode/platform010/lib/libpython3.10.so: undefined reference to `pthread_condattr_setclock@GLIBC_2.34'
//usr/local/fbcode/platform010/lib/libresolv.so.2: undefined reference to `__res_context_hostalias@GLIBC_PRIVATE'
/usr/local/fbcode/platform010/lib/libpython3.10.so: undefined reference to `sem_clockwait@GLIBC_2.34'
/usr/local/fbcode/platform010/lib/libpython3.10.so: undefined reference to `close_range@GLIBC_2.34'
//usr/local/fbcode/platform010/lib/libresolv.so.2: undefined reference to `__libc_ns_samename@GLIBC_PRIVATE'
//usr/local/fbcode/platform010/lib/libgssapi_krb5.so.2: undefined reference to `lstat@GLIBC_2.33'
```

Reviewed By: shri-khare

Differential Revision: D52703992

fbshipit-source-id: f87ab5cb4bd5874a998feac8cd5e8ac154081ac1