Fix missing NextHopGroupApi/AclApi function
Summary:
I've noticed the following compiling issue on building FBOSS OSS:

- Missing the new NextHopGroupApi.cpp in cmake from D82285162
```
/opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: libsai_tracer.a(NextHopGroupApiTracer.cpp.o): in function `facebook::fboss::wrappedNextHopGroupApi()':
NextHopGroupApiTracer.cpp:(.text+0x186f): undefined reference to `facebook::fboss::SaiNextHopGroupTraits::Attributes::AttributeArsNextHopGroupMetaData::operator()()'
/opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: NextHopGroupApiTracer.cpp:(.text+0x1898): undefined reference to `facebook::fboss::SaiNextHopGroupTraits::Attributes::AttributeArsNextHopGroupMetaData::operator()()'
collect2: error: ld returned 1 exit status
```

- Missing the new AclApi.cpp in cmake from D82568711
```
/opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: libsai_switch.a(SaiAclTableManager.cpp.o): in function `void facebook::fboss::SaiApi<facebook::fboss::AclApi>::setAttributeUnlocked<facebook::fboss::AclEntrySaiId, facebook::fboss::SaiExtensionAttribute<facebook::fboss::AclEntryAction<bool>, facebook::fboss::SaiAclEntryTraits::Attributes::AttributeActionL3SwitchCancel, facebook::fboss::SaiAcl
EntryActionBoolFalse> >(facebook::fboss::AclEntrySaiId const&, facebook::fboss::SaiExtensionAttribute<facebook::fbossCommand '['/usr/bin/cmake', '--build', '/var/FBOSS/tmp_bld_dir/build/fboss', '--target', 'install', '--config', 'RelWithDebInfo', '-j', '16']' returned non-zero exit status 1.
!! Failed
::AclEntryAction<bool>, facebook::fboss::SaiAclEntryTraits::Attributes::AttributeActionL3SwitchCancel, facebook::fboss::SaiAclEntryActionBoolFalse> const&) const':
SaiAclTableManager.cpp:(.text._ZNK8facebook5fboss6SaiApiINS0_6AclApiEE20setAttributeUnlockedINS0_13AclEntrySaiIdENS0_21SaiExtensionAttributeINS0_14AclEntryActionIbEENS0_17SaiAclEntryTraits10Attributes29AttributeActionL3SwitchCancelENS0_26SaiAclEntryActionBoolFalseEEEEEvRKT_RKT0_[_ZNK8facebook5fboss6SaiApiINS0_6AclApiEE20setAttributeUnlockedINS0_13AclEntrySaiIdENS0_21SaiExtensionAttributeINS0_14AclEntryActionIbEE
NS0_17SaiAclEntryTraits10Attributes29AttributeActionL3SwitchCancelENS0_26SaiAclEntryActionBoolFalseEEEEEvRKT_RKT0_]+0x1ff): undefined reference to `facebook::fboss::SaiAclEntryTraits::Attributes::AttributeActionL3SwitchCancel::operator()()'
/opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: libsai_store.a(SaiStore.cpp.o): in function `auto facebook::fboss::SaiApi<facebook::fboss::AclApi>::getAttribute<facebook::fboss::AclEntrySaiId, facebook::fboss::SaiExtensionAttribute<facebook::fboss::AclEntryAction<bool>, facebook::fboss::SaiAclEntryTraits::Attributes::AttributeActionL3SwitchCancel, facebook::fboss::SaiAclEntryActionBoolFals
e>, void>(facebook::fboss::AclEntrySaiId const&, std::optional<facebook::fboss::SaiExtensionAttribute<facebook::fboss::AclEntryAction<bool>, facebook::fboss::SaiAclEntryTraits::Attributes::AttributeActionL3SwitchCancel, facebook::fboss::SaiAclEntryActionBoolFalse> >&) const':
SaiStore.cpp:(.text._ZNK8facebook5fboss6SaiApiINS0_6AclApiEE12getAttributeINS0_13AclEntrySaiIdENS0_21SaiExtensionAttributeINS0_14AclEntryActionIbEENS0_17SaiAclEntryTraits10Attributes29AttributeActionL3SwitchCancelENS0_26SaiAclEntryActionBoolFalseEEEvEEDaRKT_RSt8optionalIT0_E[_ZNK8facebook5fboss6SaiApiINS0_6AclApiEE12getAttributeINS0_13AclEntrySaiIdENS0_21SaiExtensionAttributeINS0_14AclEntryActionIbEENS0_17SaiAcl
EntryTraits10Attributes29AttributeActionL3SwitchCancelENS0_26SaiAclEntryActionBoolFalseEEEvEEDaRKT_RSt8optionalIT0_E]+0x21): undefined reference to `facebook::fboss::SaiAclEntryTraits::Attributes::AttributeActionL3SwitchCancel::operator()()'
collect2: error: ld returned 1 exit status
```

- Unused handleExtensionAttributes() when building TH4 sdk using sai 1.13.2 from D81702318
```
[385/3143] Building CXX object CMakeFiles/sai_tracer.dir/fboss/agent/hw/sai/tracer/ArsProfileApiTracer.cpp.o
FAILED: CMakeFiles/sai_tracer.dir/fboss/agent/hw/sai/tracer/ArsProfileApiTracer.cpp.o
/opt/rh/gcc-toolset-12/root/usr/bin/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -DIS_OSS_BRCM_SAI=true -I/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git -I/var/FBOSS/tmp_bld_dir/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-
Kg-2xT-gNrc2cSdLOTNFVVWru0An4l2b8qYjk477fE4/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-1jS4DVcXqFYM2OrTECJCQ3Ac65trExsT2qrUoyU-7xM/include -I/var/FBOSS/tmp_bld_dir/installed/sai_impl-5gOVUpTbRtCwLw6n1vaynaH3zD-2oNS8bKznULS-Iz8/include -I/usr/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-Q5zzc2RQRj59kRhx3KTJRk48v7umDlgAY0pBya86j3I/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-haFCmXqlA1s
aLIh6PD4alnwnBWtJnBimC9VjYVEDFW0/include -I/var/FBOSS/tmp_bld_dir/installed/libyaml-3XvvCqwj2t50XaNSY45LfDhQoHymVmOE5-Qex0jzm4A/include -I/var/FBOSS/tmp_bld_dir/installed/exprtk-ZxfD40_AoSCqr_jof1iXBe2Izq1HhlJWfnldT_NWss4 -I/var/FBOSS/tmp_bld_dir/installed/libgpiod-W0I-MJOWG7ZFghIY89Z-z6XRLlAZtsDQj99WvrYW9i4/include -I/var/FBOSS/tmp_bld_dir/installed/sai_impl-5gOVUpTbRtCwLw6n1vaynaH3zD-2oNS8bKznULS-Iz8 -I/var/FB
OSS/tmp_bld_dir/installed/googletest-YpfIZIX53B0cH99_Jqvx8ROhmbEaxYaivD_VGqC1-eE/include -I/var/FBOSS/tmp_bld_dir/build/fboss -isystem /var/FBOSS/tmp_bld_dir/installed/gflags-Xf9DMhzYv1TptCg5oUrY1gAt5_v8yE1u1Y4XGY4Ueak/include -isystem /var/FBOSS/tmp_bld_dir/installed/glog-EDjm2qK7zlVfmb2mL8njHRbLhwO9Y41fpFzqU5wG1TQ/include -isystem /var/FBOSS/tmp_bld_dir/installed/folly/include -isystem /var/FBOSS/tmp_bld_dir/i
nstalled/boost-yPW7svNze8lcNPfinAa3VU5uaByk7s_aS0pCbiRbR1I/include -isystem /var/FBOSS/tmp_bld_dir/installed/fb303/include -isystem /var/FBOSS/tmp_bld_dir/installed/fmt-IA5zUYM4sz8ByeokQ5_KF2JlO2UEAtuNBO6aVTQu7PA/include -isystem /var/FBOSS/tmp_bld_dir/installed/fast_float-Xuo0xxgMCHo-6V0BBTfLgPEYpHWFtJ9dtY5bkK03_ZQ/include -isystem /usr/include/libdwarf-0 -isystem /var/FBOSS/tmp_bld_dir/installed/fbthrift/inclu
de -isystem /var/FBOSS/tmp_bld_dir/installed/wangle/include -isystem /var/FBOSS/tmp_bld_dir/installed/fizz/include -isystem /var/FBOSS/tmp_bld_dir/installed/mvfst/include -DSAI_VERSION_10_2_0_0_ODP -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -std=gnu++20 -DSAI_VER_MAJOR=1   -DSAI_VER_MINOR=13    -DSAI_VER_RELEASE=2 -fsized-deallocation -MD -MT CMakeFiles/sai
_tracer.dir/fboss/agent/hw/sai/tracer/ArsProfileApiTracer.cpp.o -MF CMakeFiles/sai_tracer.dir/fboss/agent/hw/sai/tracer/ArsProfileApiTracer.cpp.o.d -o CMakeFiles/sai_tracer.dir/fboss/agent/hw/sai/tracer/ArsProfileApiTracer.cpp.o -c /var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/agent/hw/sai/tracer/ArsProfileApiTracer.cpp
/var/FBOSS/tmp_bld_dir/repos/github.com-facebook-fboss.git/fboss/agent/hw/sai/tracer/ArsProfileApiTracer.cpp:50:6: error: ‘void {anonymous}::handleExtensionAttributes()’ defined but not used [-Werror=unused-function]
   50 | void handleExtensionAttributes() {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Differential Revision: D83006389

fbshipit-source-id: b0c60fb80cbf1748aa41da2cfec1ce5d2947b91e