Add new ConfigValidator to fw_util cmake
Summary:
Need to add this to unbreak OSS builds:
```
[904/916] Linking CXX executable fw_util
FAILED: fw_util
...
/opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: libfw_util_libs.a(FwUtilImpl.cpp.o): in function `facebook::fboss::platform::fw_util::FwUtilImpl::init()':
FwUtilImpl.cpp:(.text+0x1a57): undefined reference to `facebook::fboss::platform::fw_util::ConfigValidator::isValid(facebook::fboss::platform::fw_util_config::FwUtilConfig const&)'
collect2: error: ld returned 1 exit status
```

Reviewed By: ezeob002

Differential Revision: D81358115

fbshipit-source-id: 35fed8a6375a2933389ef447e6c2d9553af17fa4