Fix FBOSS OSS build issues
Summary:
- D92638975 did some refactor work for fboss2 show fsdb classes
But unnecessarily use ServiceRouter.h in these classes, and ServiceRouter.h is not open sourced. Which caused the following errors:
```
-c /var/FBOSS/fboss/fboss/cli/fboss2/commands/show/fsdb/CmdShowFsdbDataCommon.cpp
/var/FBOSS/fboss/fboss/cli/fboss2/commands/show/fsdb/CmdShowFsdbDataCommon.cpp:17:10: fatal error: servicerouter/client/cpp2/ServiceRouter.h: No such file or directory
   17 | #include <servicerouter/client/cpp2/ServiceRouter.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-c /var/FBOSS/fboss/fboss/cli/fboss2/commands/show/fsdb/CmdShowFsdbPublishers.cpp
/var/FBOSS/fboss/fboss/cli/fboss2/commands/show/fsdb/CmdShowFsdbPublishers.cpp:17:10: fatal error: servicerouter/client/cpp2/ServiceRouter.h: No such file or directory
   17 | #include "servicerouter/client/cpp2/ServiceRouter.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-c /var/FBOSS/fboss/fboss/cli/fboss2/commands/show/fsdb/CmdShowFsdbSubscribers.cpp
/var/FBOSS/fboss/fboss/cli/fboss2/commands/show/fsdb/CmdShowFsdbSubscribers.cpp:18:10: fatal error: servicerouter/client/cpp2/ServiceRouter.h: No such file or directory
   18 | #include "servicerouter/client/cpp2/ServiceRouter.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Reviewed By: huruinan, shiva-menta

Differential Revision: D92793807

fbshipit-source-id: 03b8f84cb3d76792ba05998e3a797379985d46eb