Fix missing setup_thrift_prod library for sai_agent_scale_test
Summary:
Vendor reported the following compilation error when building sai_agent_scale_test-sai_impl
```
0W_CsE/lib64/libdwarf.a  /usr/lib64/libiberty.a  /usr/lib64/libsodium.so  -ldl  /usr/lib64/libxxhash.so  /usr/lib64/libnl-3.so && :
/opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: libsw_agent_initializer.a(SwAgentInitializer.cpp.o): in function `facebook::fboss::SwAgentInitializer::initAgent(facebook::fboss::HwSwitchCallback*, facebook::fboss::HwWriteBehavior const&)':
SwAgentInitializer.cpp:(.text+0x102a): undefined reference to `facebook::fboss::createThriftHandler(facebook::fboss::SwSwitch*)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Command '['/usr/bin/cmake', '--build', '/build/scratch/build/fboss', '--target', 'sai_agent_scale_test-sai_impl', '--config', 'MinSizeRel', '-j', '15']' returned non-zero exit status 1.
!! Failed
```
This is due to a recent change of D82189621, which introduced the new util function but missed adding the dependency in this target.

Unfortunately, our on-diff doesn't seem to build the scale tests. KevinYakar: can you help adding the scale test when building agent binaries for on-diff signal

Reviewed By: shri-khare

Differential Revision: D82582533

fbshipit-source-id: ed86bf88d4b10edf0147fa90228a3fcc43290640