Fix missing hyper_port_test_utils in sai_agent_hw_test
Summary:
D90350445 introduced the new hyper port logic in AgentL3ForwardingTests.cpp but forgot to include the `hyper_port_test_utils` library for OSS
Which cause my agent oss conveyor run failed: https://www.internalfb.com/sandcastle/workflow/3301138526875731303/artifact/actionlog.3301138527086357951.stdout.1?selectedLines=636-643-1-1
```
[147/147] Linking CXX executable sai_agent_hw_test-sai_impl
FAILED: sai_agent_hw_test-sai_impl
...
AgentL3ForwardingTests.cpp:(.text+0x17644): undefined reference to `facebook::fboss::utility::getHyperPortMembers(std::shared_ptr<facebook::fboss::SwitchState> const&, facebook::fboss::PortID)'
```

Checked the oss on-diff job but somehow that job skipped building sai_agent_hw_test-fake, which could have caught this issue
https://www.internalfb.com/sandcastle/workflow/662029145236280551/artifact/actionlog.662029145442268935.stdout.1?selectedLines=589-611-1-1

Need to debug why on-diff OSS job skipped building this test binary and others too.
For now let's land this diff to unblock CI

Reviewed By: daiwei1983

Differential Revision: D90748127

fbshipit-source-id: bfa0719f800d26838d95d960d6778dc905b0edc6