include "this" in implicit lambda capture in sw switch
Summary:
As titled, include "this" in implicit lambda capture in sw switch

This is towards enabling co-routines on FBOSS OSS + moving to C++20 + building sw and hw agent in OSS

Error seen:
```
 error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20
```

Reviewed By: shri-khare

Differential Revision: D50465458

fbshipit-source-id: 733eea576f54a9c2dcfad28e5e4db0be6a4748bf