Replace all common/process with folly/Subprocess
Summary:
Recently we allowed Codemod to delete common/process/Process.h in D77790622 since our non-OSS buck is no longer using this file
However for OSS, we still need this. Therefore, I started noticed the following error when running getdeps
```
$ time ./build/fbcode_builder/getdeps.py build --allow-system-packages --extra-cmake-defines='{"CMAKE_BUILD_TYPE": "MinSizeRel", "CMAKE_CXX_STANDARD": "20"}' --scratch-path /var/FBOSS/tmp_bld_dir --num-jobs 16 --src-dir . fboss
 ...
[1/1081] Building CXX object CMakeFiles/multinode_tests.dir/fboss/agent/test/MultiNodeLacpTests.cpp.o
FAILED: CMakeFiles/multinode_tests.dir/fboss/agent/test/MultiNodeLacpTests.cpp.o
/usr/bin/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -DIS_OSS_BRCM_SAI=true -I/var/FBOSS/fboss -I/var/FBOSS/tmp_bld_dir/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-gDDrUeYzXCyPGUdKbnQHN1bXf4lYpBQO8r8ZeaTW9R0/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-hhw1PA0WexK3dhq5mk5An5bOV2di1ttV6CZI_cin-7k/include -I/var/FBOSS/tmp_bld_dir/installed/sai_impl-wwFuGm1be-L5uDSSzjf3KAdtZBlsEJQZFNydsrQn2k8/include -I/usr/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-whtmrPlJs8hIRpwOqIyTUwmu8_LdyvkOl8DV_Z12tYY/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-hjAsUmBD-0-wfiFk0Tn0rJwsyQeTEUVcQGqDSxQK50I/include -I/var/FBOSS/tmp_bld_dir/installed/libyaml-8LXv2CSDMLX1GERjRWihBh1wk6jJn06yPk32l0qiMjY/include -I/var/FBOSS/tmp_bld_dir/installed/exprtk-HI3d9LHfz-zHyk7DhL_UIawNajHepWbxjg9SPq0do9c -I/var/FBOSS/tmp_bld_dir/installed/libgpiod-6qAN3q2-8KMnbBB_0CpsBBcpvkrf9hwP1T26w3iv1io/include -I/var/FBOSS/tmp_bld_dir/installed/sai_impl-wwFuGm1be-L5uDSSzjf3KAdtZBlsEJQZFNydsrQn2k8 -I/var/FBOSS/tmp_bld_dir/build/fboss -isystem /var/FBOSS/tmp_bld_dir/installed/gflags-qab5FKjlCBmUMXtzK3x5T4Wx5cnMJnazeS73sYLJ72U/include -isystem /var/FBOSS/tmp_bld_dir/installed/glog-tCm1cg2zewXtXRYWhLj-rhVix1tuT6wmR-xQP1Cbrzw/include -isystem /var/FBOSS/tmp_bld_dir/installed/folly/include -isystem /var/FBOSS/tmp_bld_dir/installed/boost-bDFME8k4Y3xrApUdeK8pjWoOB1bB6h7YGg7NBnogxL8/include -isystem /var/FBOSS/tmp_bld_dir/installed/fb303/include -isystem /var/FBOSS/tmp_bld_dir/installed/googletest-REIrhOEYWy6FUcnaovx3sxYQRT4EQTxr7Npj_U_NoYM/include -isystem /var/FBOSS/tmp_bld_dir/installed/fast_float-vgXCrsaTU4d7bTdzN9ELy98-8hgrwq3xhIztW07k48Y/include -isystem /usr/include/libdwarf-0 -isystem /var/FBOSS/tmp_bld_dir/installed/fmt-_2dqCArwtolk8iJ7gPzuVWNe2Kc9re3LaIAFeztL88k/include -isystem /var/FBOSS/tmp_bld_dir/installed/fbthrift/include -isystem /var/FBOSS/tmp_bld_dir/installed/wangle/include -isystem /var/FBOSS/tmp_bld_dir/installed/fizz/include -isystem /var/FBOSS/tmp_bld_dir/installed/mvfst/include -DSAI_VERSION_11_7_0_0_ODP -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -std=gnu++20 -fsized-deallocation -MD -MT CMakeFiles/multinode_tests.dir/fboss/agent/test/MultiNodeLacpTests.cpp.o -MF CMakeFiles/multinode_tests.dir/fboss/agent/test/MultiNodeLacpTests.cpp.o.d -o CMakeFiles/multinode_tests.dir/fboss/agent/test/MultiNodeLacpTests.cpp.o -c /var/FBOSS/fboss/fboss/agent/test/MultiNodeLacpTests.cpp
/var/FBOSS/fboss/fboss/agent/test/MultiNodeLacpTests.cpp:32:10: fatal error: common/process/Process.h: No such file or directory
   32 | #include "common/process/Process.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Instead of bringing back this common/process/Process.h which has empty implementation but just returning true,
I decided to replace all the clients which use such helper function to use folly/Subprocess to handle executing commands logic

Reviewed By: KevinYakar

Differential Revision: D78357856

fbshipit-source-id: e897dcb254892a5a02b19cb8485d6bd763f91a58