Fixed the usage of bitwise or '|' instead of logical or '||'
Summary:
The build fails due to this error:

  buck2 build mode/opt fboss/qsfp_service:qsfp_service

  bcode/fboss/qsfp_service/module/QsfpModule.cpp:567:9: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]

Reviewed By: harshitgulati18

Differential Revision:
D50661329

Privacy Context Container: L1125642

fbshipit-source-id: 0e560287107e11dc23c1551c33aba119c7283d38