SAI replayer build failure fix
Summary:
Build failing for certain cases where the functions are not being used
```
buck2 build --show-output @//mode/opt //fboss/agent/hw/sai/tracer/run:sai_replayer-brcm-10.2.0.0_odp
File changed: fbcode//fboss/agent/hw/sai/tracer/run/SaiLog.cpp
Action failed: fbcode//fboss/agent/hw/sai/tracer/run:sai_replayer-brcm-10.2.0.0_odp (cxx_compile SaiLog.cpp)
Local command returned non-zero exit code 1
Reproduce locally: `env -C "$(buck2 root --kind project)" -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/fbcode/a218449d8d694beb/ ...<omitted>... nt/hw/sai/tracer/run/__sai_replayer-brcm-10.2.0.0_odp__/output_artifacts/__objects__/SaiLog.cpp.dwo' (run `buck2 log w
hat-failed` to get the full command)`
stdout:
stderr:
fbcode/fboss/agent/hw/sai/tracer/run/SaiLog.cpp:63:13: error: unused function 'attrCheck' [-Werror,-Wunused-function]
   63 | inline void attrCheck(sai_attribute_t *expected, sai_attribute_t *actual, int32_t num, int count) {
      |             ^~~~~~~~~
1 error generated.
```

Reviewed By: jasmeetbagga

Differential Revision: D101111743

fbshipit-source-id: 5431849a81579b7136e1e33a27ef3eb24e407d3a