Fix OSS build failure due to missing attr
Summary:
Fix OSS build failure due to missing attr

```
FAILED: sai_link_test-fake
: && /bin/c++ -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -Wl,-wrap,sai_api_query -Wl,-wrap,sai_api_initialize -Wl,-wrap,sai_api_uninitialize -Wl,-wrap,sai_get_object_key CMakeFiles/sai_link_test-fake.dir/fboss/agent/hw/sai/hw_test/HwTestFabricUtils.cpp.o CMakeFiles/sai_link_test-fake.dir/fboss/agent/test/link_tests/SaiLinkTest.cpp.o -o sai_link_test-fake  -Wl,-rpath,/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/libyaml-TY3Te3S5ejn-jjt3UP2vfLUbjC90dc6PD7psoP2Mts8/lib:/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/gflags-FHGtz15ipgdtBy8VDWwU07RNW_0yBukAYrcBYzpi1g8/lib:/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/glog-kCh757cr82SAdy4c1gcwKKJY2dg-eTnUsnnFYmqPNS4/lib64:  -Wl,--whole-archive  libfake_sai.a  liblink_tests.a  libagent_config_cpp2.a  libsai_platform.a  libsai_ecmp_utils.a  libsai_port_utils.a  libsai_traced_api.a  libtrap_packet_utils.a  -Wl,--no-whole-archive  libref_map.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/googletest-7JnJT5CgY1LVTPmQfwvncdoArZXAShZsSsQa9C0lCU4/lib64/libgmock_main.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/googletest-7JnJT5CgY1LVTPmQfwvncdoArZXAShZsSsQa9C0lCU4/lib64/libgmock.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/googletest-7JnJT5CgY1LVTPmQfwvncdoArZXAShZsSsQa9C0lCU4/lib64/libgtest.a  libsai_fake_extensions.a  libagent_test_lib.a  libqsfp_service_client.a  libmonolithic_agent_initializer.a  libsw_agent_initializer.a  libsetup_thrift.a  libqos_test_utils.a  libmain.a  libfboss_common_init.a  libload_balancer_utils.a  libolympic_qos_utils.a  libnetwork_ai_qos_utils.a  libtraffic_policy_utils.a  libqueue_test_utils.a  libcopp_test_utils.a  libload_balancer_test_utils.a  libhw_packet_utils.a  libpacket_snooper.a  libpacket_factory.a  libsflow_structs.a  libresourcelibutil.a  libhw_switch_ensemble.a  libhw_link_state_toggler.a  libmultiswitch_test_server.a  libsplit_agent_thrift_syncer.a  libmultiswitch_service.a  libpkt_test_utils.a  libconfig_factory.a  libconfig_utils.a  libport_test_utils.a  libvoq_test_utils.a  libecmp_helper.a  libneighbor_test_utils.a  libtest_ensemble_if.a  libhwagent.a  libfboss_init.a  liblinkstate_toggler.a  liblink_test_production_features_cpp2.a  libtrunk_utils.a  libsai_platform.a  libsai_switch.a  libthrift_handler.a  libdiag_shell.a  libsai_platform.a  libsai_switch.a  libthrift_handler.a  libdiag_shell.a  libdsfnode_utils.a  libwedge_led_utils.a  libfboss_i2c_lib.a  libi2c_controller_stats_cpp2.a  /usr/lib64/libusb-1.0.so  /usr/lib64/libcurl.so  libbcm_yaml_config.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/yaml-cpp-qO3lWZVT4UgBNn_iIPaAGXVLKmz02GwHst9pmDKpm0o/lib/libyaml-cpp.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/libyaml-TY3Te3S5ejn-jjt3UP2vfLUbjC90dc6PD7psoP2Mts8/lib/libyaml.so  libled_structs_types_cpp2.a  libled_mapping_cpp2.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/googletest-7JnJT5CgY1LVTPmQfwvncdoArZXAShZsSsQa9C0lCU4/lib64/libgmock_main.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/googletest-7JnJT5CgY1LVTPmQfwvncdoArZXAShZsSsQa9C0lCU4/lib64/libgmock.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/googletest-7JnJT5CgY1LVTPmQfwvncdoArZXAShZsSsQa9C0lCU4/lib64/libgtest.a  -Wl,--unresolved-symbols=ignore-all  libhw_trunk_counters.a  libhw_port_fb303_stats.a  libhw_resource_stats_publisher.a  libprbs_stats_entry.a  libsai_store.a  libref_map.a  -Wl,--unresolved-symbols=report-all  libhandler.a  libpkt.a  liblog_thrift_call.a  libthrifthandler_utils.a  libsai_ctrl_cpp2.a  libsai_repl.a  libsai_api.a  libpython_repl.a  /usr/lib64/libpython3.9.so  -lutil  libaddress_util.a  libsai_tracer.a  libsai_version.a  liblogging_util.a  libfunction_call_time_reporter.a  libacl_test_utils.a  libasic_test_utils.a  libcore.a  libloadbalancer_utils.a  libhw_cpu_fb303_stats.a  libhw_fb303_stats.a  libcounter_utils.a  libmonolithic_switch_handler.a  libhw_switch.a  libhw_switch_warmboot_helper.a  libsw_switch_warmboot_helper.a  libasync_logger.a  libcommon_file_utils.a  libhw_asic_table.a  libwarm_boot_file_utils.a  libplatform_base.a  libhw_switch_fb303_stats.a  libcommon_utils.a  libhw_switch_handler.a  libhw_write_behavior.a  libvoq_utils.a  libcapture.a  libpacket.a  libpktutil.a  libstats.a  libpacket_observer.a  libdiag_cmd_filter.a  liblldp.a  liblldp_structs_cpp2.a  libmultiswitch_ctrl_cpp2.a  librestart_time_tracker.a  libutils.a  libload_agent_config.a  libasic_utils.a  libagent_dir_util.a  libroute_update_wrapper.a  libswitchid_scope_resolver.a  libswitchinfo_utils.a  libexponential_back_off.a  libphy_utils.a  libbidirectional_packet_stream.a  libasync_packet_transport.a  libpacket_stream_cpp2.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/iproute2-uZlREBVTwro6XgcS1k92RX1WsnBeZ-bwcHp9vBd4xeQ/lib/libnetlink.a  /usr/lib64/libnl-3.so  /usr/lib64/libnl-route-3.so  libthread_heartbeat.a  libplatform_mapping_utils.a  libfake_test_platform_mapping.a  libminipack_platform_mapping.a  libelbert_platform_mapping.a  libyamp_platform_mapping.a  libfuji_platform_mapping.a  libgalaxy_platform_mapping.a  libwedge100_platform_mapping.a  libwedge40_platform_mapping.a  libwedge400_platform_utils.a  libwedge400c_platform_utils.a  libdarwin_platform_mapping.a  libwedge400_platform_mapping.a  libwedge400c_platform_mapping.a  libmorgan_platform_mapping.a  libmeru400biu_platform_mapping.a  libmeru400bia_platform_mapping.a  libmeru400bfu_platform_mapping.a  libmeru800bia_platform_mapping.a  libswitch_asics.a  libversion_util.a  libmeru800bfa_platform_mapping.a  libproduct_info.a  libyangra_platform_mapping.a  libminipack3n_platform_mapping.a  libmontblanc_platform_mapping.a  libjanga800bic_platform_mapping.a  libtahan800bc_platform_mapping.a  libicecube800bc_platform_mapping.a  libplatform_mapping.a  libfboss_config_utils.a  libexternal_phy.a  libagent_features.a  libhw_ctrl_cpp2.a  libl2learn_event_observer.a  libagent_fsdb_sync_manager.a  libtuple_utils.a  libfsdb_syncer.a  libfsdb_pub_sub.a  libfsdb_stream_client.a  libthrift_service_client.a  libqsfp_cpp2.a  libcommon_thrift_utils.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fb303/lib/libfb303.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fb303/lib/libfb303_thrift_cpp.a  libfsdb_cpp2.a  libfsdb_flags.a  libcow_storage_mgr.a  libfboss_event_base.a  libphy_snapshot_manager.a  libsnapshot_manager.a  libalert_logger.a  libasync_filewriter_factory.a  libbuild_info_wrapper.a  libecmp_resource_manager.a  libfib_helpers.a  libfib_updater.a  libstate.a  libfsdb_helper.a  libstate.a  libfsdb_helper.a  libhwswitch_matcher.a  liblacp_types.a  libfsdb_model.a  libfsdb_model_thriftpath_cpp2.a  libfsdb_model_cpp2.a  libagent_config_cpp2.a  libswitch_reachability_cpp2.a  libqsfp_state_cpp2.a  libqsfp_config_cpp2.a  libtransceiver_validation_cpp2.a  libpim_state_cpp2.a  libport_state_cpp2.a  libqsfp_stats_cpp2.a  libsensor_service_stats_cpp2.a  libthriftpath_lib.a  libfsdb_utils.a  libcow_storage.a  libstorage.a  libstandalone_rib.a  liblabel_forwarding_action.a  libstate_utils.a  liberror.a  libthrift_cow_nodes.a  libnodebase.a  libfboss_error.a  libfboss_types.a  libthrift_cow_serializer.a  libthrift_cow_visitors.a  /usr/lib64/libre2.so  libfsdb_oper_cpp2.a  libfsdb_common_cpp2.a  libpatch_cpp2.a  libcow_visitor_results_cpp2.a  libnetwork_to_route_map.a  libradix_tree.a  libaddress_utils.a  libthrift_method_rate_limit.a  libswitch_state_cpp2.a  libctrl_cpp2.a  libplatform_config_cpp2.a  libbcm_config_cpp2.a  libasic_config_cpp2.a  libasic_config_v2_cpp2.a  libproduct_info_cpp2.a  libagent_stats_cpp2.a  libphy_cpp2.a  libswitch_config_cpp2.a  libcommon_cpp2.a  libnetwork_address_cpp2.a  libfboss_common_cpp2.a  libmpls_cpp2.a  libfb303_cpp2.a  libio_stats_cpp2.a  libhardware_stats_cpp2.a  libmka_structs_cpp2.a  libsensor_service_cpp2.a  libfboss_cpp2.a  libsensor_config_cpp2.a  liboptic_cpp2.a  libtransceiver_cpp2.a  liblink_cpp2.a  libprbs_cpp2.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftcpp2.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftfrozen2.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftmetadata.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftanyrep.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthrifttype.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftprotocol.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftprotocol.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libasync.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libruntime.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libtransport.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/librpcmetadata.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libconcurrency.a  /lib64/libzstd.so  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/wangle/lib/libwangle.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthrift-core.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthrifttyperep.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftannotation.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libserverdbginfo.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_server_async_tran.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_server.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_server_state.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_dsr_frontend.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_dsr_types.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_fizz_handshake.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_transport.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_buf_accessor.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_datagram_handler.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_batch_writer.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_cc_algo.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_codec_pktrebuilder.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_ack_scheduler.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_happyeyeballs.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_async_udp_socket.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_events.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_looper.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_observer.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_ack_handler.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_loss.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_pacing_functions.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_simple_frame_functions.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_functions.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_codec_pktbuilder.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_stream.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_flowcontrol.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_qlogger.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_stream_functions.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_machine.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_codec.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_handshake.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_codec_packet_number_cipher.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_codec_decode.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_codec_types.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_exception.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fizz/lib/libfizz.a  /usr/lib64/libsodium.so  /usr/lib64/libz.so  /usr/lib64/librt.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/liboqs-lqANo3b050oo5BQbQZWrgKe3541kV1KFfUaiziVRgJk/lib64/liboqs.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_bufutil.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_http_priority_queue.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_round_robin.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_transport_knobs.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_constants.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_transport_settings_functions.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/folly/lib/libfolly.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/lib64/libfmt.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/boost-ekzv3-LMUT7ciCQTZ8O6VgxUmubclRMMSvqk1pfNRpU/lib/libboost_context.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/boost-ekzv3-LMUT7ciCQTZ8O6VgxUmubclRMMSvqk1pfNRpU/lib/libboost_filesystem.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/boost-ekzv3-LMUT7ciCQTZ8O6VgxUmubclRMMSvqk1pfNRpU/lib/libboost_atomic.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/boost-ekzv3-LMUT7ciCQTZ8O6VgxUmubclRMMSvqk1pfNRpU/lib/libboost_program_options.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/boost-ekzv3-LMUT7ciCQTZ8O6VgxUmubclRMMSvqk1pfNRpU/lib/libboost_regex.a  -licudata  -licui18n  -licuuc  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/boost-ekzv3-LMUT7ciCQTZ8O6VgxUmubclRMMSvqk1pfNRpU/lib/libboost_system.a  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/boost-ekzv3-LMUT7ciCQTZ8O6VgxUmubclRMMSvqk1pfNRpU/lib/libboost_thread.a  /usr/lib64/libdouble-conversion.so  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/gflags-FHGtz15ipgdtBy8VDWwU07RNW_0yBukAYrcBYzpi1g8/lib/libgflags.so.2.2.2  /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/glog-kCh757cr82SAdy4c1gcwKKJY2dg-eTnUsnnFYmqPNS4/lib64/libglog.so  /usr/lib64/libevent.so  /usr/lib64/libz.so  /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  /usr/lib64/libbz2.so  /usr/lib64/liblzma.so  /usr/lib64/liblz4.so  /usr/lib64/libzstd.so  /usr/lib64/libsnappy.so  /usr/lib64/libdwarf.so  /usr/lib64/libiberty.a  /usr/lib64/libaio.so  /usr/lib64/libsodium.so  -ldl  /usr/lib64/libunwind.so  /usr/lib64/libxxhash.so && :
/bin/ld: libsai_tracer.a(SwitchApiTracer.cpp.o): in function `(anonymous namespace)::handleExtensionAttributes()':
SwitchApiTracer.cpp:(.text+0x2743): undefined reference to `facebook::fboss::SaiSwitchTraits::Attributes::AttributeAsicRevision::operator()()'
```

Reviewed By: jasmeetbagga

Differential Revision: D76388886

fbshipit-source-id: 54e9ca0b78b7ca0923c68f173cc0aff4a11d67dd