Use __attribute__((unused)) on unused fucntion: deserializeSflowPacket
Summary:
IMHO,Buck has a more relaxing check on unused function, which is only marked as a warning
But for building OSS, it will fail compiling
https://www.internalfb.com/sandcastle/workflow/616993148960850082
```
[226/372] Building CXX object CMakeFiles/agent_hw_test_src.dir/fboss/agent/test/agent_hw_tests/AgentSflowMirrorTest.cpp.o
FAILED: CMakeFiles/agent_hw_test_src.dir/fboss/agent/test/agent_hw_tests/AgentSflowMirrorTest.cpp.o
/opt/rh/gcc-toolset-12/root/usr/bin/g++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -I/var/FBOSS/fboss -I/var/FBOSS/tmp_bld_dir/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-BKAHPQs9qewPBb3JWtiR3H4hXRf1wVJ_zjhSmjHT2L4/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-NsCzqfOofR1AnhHHbwqV46ajHxZgD1m_FKhRqD9uVng/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-NsCzqfOofR1AnhHHbwqV46ajHxZgD1m_FKhRqD9uVng/experimental -I/usr/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-k3EjRS6jCDcH8tkpFFIxMlLmFggOJk_TFmrjGHokSC0/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-Bu24PX2lS0W4Ll4MJNWWfr6XOnlOMjqPv1c1UIk9T8s/include -I/var/FBOSS/tmp_bld_dir/installed/libyaml-cxUgJoi8NNG3ctyXyZCLBXx3kFbyS75xkjaiSS4fZl0/include -I/var/FBOSS/tmp_bld_dir/installed/exprtk-6qxcGRhBmgOXcbY1fnc3-gDWHF_lpIyNCdLwz-aaGao -I/var/FBOSS/tmp_bld_dir/installed/libgpiod-KLa7TQpN3l4NCI1VImJxI7oB3fm9VaVjN6szQKJD6k4/include -I/var/FBOSS/tmp_bld_dir/build/fboss -isystem /var/FBOSS/tmp_bld_dir/installed/gflags-BHEbaDqHQhJ3bReXNtUg-60gyywM1b0qpA0VboZEud4/include -isystem /var/FBOSS/tmp_bld_dir/installed/glog-hJwq_2nHTaP0M7249C6m_hAYv5LiRI0Mmn8rWBgDzTg/include -isystem /var/FBOSS/tmp_bld_dir/installed/folly/include -isystem /var/FBOSS/tmp_bld_dir/installed/boost-fycuet-5B-5_0oMZ_kPknJRLJZyy22sdy5K0QVGqBdc/include -isystem /var/FBOSS/tmp_bld_dir/installed/fb303/include -isystem /var/FBOSS/tmp_bld_dir/installed/googletest-Qva1sgckFYQmZ7OoSBDn2bJHSorjgcToZx0nnLhQ-xE/include -isystem /var/FBOSS/tmp_bld_dir/installed/fmt-9-QR8Ls5R769ldWXy_pwx5W85nLHNBJdZ8mBPleBQVU/include -isystem /var/FBOSS/tmp_bld_dir/installed/fast_float-Limz43H4XXzrZjwTkoQo8KsXI3JolmdDZkC6BBCW0Og/include -isystem /usr/include/libdwarf-0 -isystem /var/FBOSS/tmp_bld_dir/installed/fbthrift/include -isystem /var/FBOSS/tmp_bld_dir/installed/wangle/include -isystem /var/FBOSS/tmp_bld_dir/installed/fizz/include -isystem /var/FBOSS/tmp_bld_dir/installed/mvfst/include -isystem /usr/include/python3.9 -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -std=gnu++20 -fsized-deallocation -ftemplate-backtrace-limit=0 -MD -MT CMakeFiles/agent_hw_test_src.dir/fboss/agent/test/agent_hw_tests/AgentSflowMirrorTest.cpp.o -MF CMakeFiles/agent_hw_test_src.dir/fboss/agent/test/agent_hw_tests/AgentSflowMirrorTest.cpp.o.d -o CMakeFiles/agent_hw_test_src.dir/fboss/agent/test/agent_hw_tests/AgentSflowMirrorTest.cpp.o -c /var/FBOSS/fboss/fboss/agent/test/agent_hw_tests/AgentSflowMirrorTest.cpp
/var/FBOSS/fboss/fboss/agent/test/agent_hw_tests/AgentSflowMirrorTest.cpp:64:19: error: ‘facebook::fboss::{anonymous}::SflowPacketParsed facebook::fboss::{anonymous}::deserializeSflowPacket(const folly::IOBuf*)’ defined but not used [-Werror=unused-function]
   64 | SflowPacketParsed deserializeSflowPacket(const folly::IOBuf* buf) {
      |                   ^~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

IMHO, I'd like to keep this check as error cause we don't want an unused function in our code because of reliability and better maintenance.
For now, if a unused function needs to add it into our code, I'd suggest to explicitly use `__attribute__((unused))` until we add the logic to call such function

Differential Revision: D85359089

fbshipit-source-id: e13173561551a6ecb325dcd95285f2fe81c695c0