Add required deps for fake sai build
Summary:
We were missing some deps for fake sai builds due to our custom agent thrift libs target missing something:
```
[16/569] Building CXX object CMakeFiles/l2learn_observer_util.dir/fboss/agent/test/utils/L2LearningUpdateObserverUtil.cpp.o
FAILED: CMakeFiles/l2learn_observer_util.dir/fboss/agent/test/utils/L2LearningUpdateObserverUtil.cpp.o
/opt/rh/gcc-toolset-12/root/usr/bin/g++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -I/var/FBOSS/fboss -I/var/FBOSS/tmp_bld_dir/installed/fatal -I/var/FBOSS/tmp_bld_dir/installed/nlohmann-json-BKAHPQs9qewPBb3JWtiR3H4hXRf1wVJ_zjhSmjHT2L4/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-NsCzqfOofR1AnhHHbwqV46ajHxZgD1m_FKhRqD9uVng/include -I/var/FBOSS/tmp_bld_dir/installed/libsai-NsCzqfOofR1AnhHHbwqV46ajHxZgD1m_FKhRqD9uVng/experimental -I/usr/include/libnl3 -I/var/FBOSS/tmp_bld_dir/installed/iproute2-k3EjRS6jCDcH8tkpFFIxMlLmFggOJk_TFmrjGHokSC0/include -I/var/FBOSS/tmp_bld_dir/installed/yaml-cpp-Bu24PX2lS0W4Ll4MJNWWfr6XOnlOMjqPv1c1UIk9T8s/include -I/var/FBOSS/tmp_bld_dir/installed/libyaml-iH72A_zbnOR3bGCgaHRx4n6cvsVFucOBWIhufAJTmsA/include -I/var/FBOSS/tmp_bld_dir/installed/exprtk-6qxcGRhBmgOXcbY1fnc3-gDWHF_lpIyNCdLwz-aaGao -I/var/FBOSS/tmp_bld_dir/installed/libgpiod-9XHBA6rtoINSaP9rQnw2JTB5muiLGOGB51FVnz9_TTE/include -I/var/FBOSS/tmp_bld_dir/installed/googletest-Qva1sgckFYQmZ7OoSBDn2bJHSorjgcToZx0nnLhQ-xE/include -I/var/FBOSS/tmp_bld_dir/build/fboss -isystem /var/FBOSS/tmp_bld_dir/installed/gflags-BHEbaDqHQhJ3bReXNtUg-60gyywM1b0qpA0VboZEud4/include -isystem /var/FBOSS/tmp_bld_dir/installed/glog-hJwq_2nHTaP0M7249C6m_hAYv5LiRI0Mmn8rWBgDzTg/include -isystem /var/FBOSS/tmp_bld_dir/installed/folly/include -isystem /var/FBOSS/tmp_bld_dir/installed/boost-fycuet-5B-5_0oMZ_kPknJRLJZyy22sdy5K0QVGqBdc/include -isystem /var/FBOSS/tmp_bld_dir/installed/fb303/include -isystem /var/FBOSS/tmp_bld_dir/installed/fmt-9-QR8Ls5R769ldWXy_pwx5W85nLHNBJdZ8mBPleBQVU/include -isystem /var/FBOSS/tmp_bld_dir/installed/fast_float-Limz43H4XXzrZjwTkoQo8KsXI3JolmdDZkC6BBCW0Og/include -isystem /usr/include/libdwarf-0 -isystem /var/FBOSS/tmp_bld_dir/installed/fbthrift/include -isystem /var/FBOSS/tmp_bld_dir/installed/wangle/include -isystem /var/FBOSS/tmp_bld_dir/installed/fizz/include -isystem /var/FBOSS/tmp_bld_dir/installed/mvfst/include -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -std=gnu++20 -fsized-deallocation -ftemplate-backtrace-limit=0 -MD -MT CMakeFiles/l2learn_observer_util.dir/fboss/agent/test/utils/L2LearningUpdateObserverUtil.cpp.o -MF CMakeFiles/l2learn_observer_util.dir/fboss/agent/test/utils/L2LearningUpdateObserverUtil.cpp.o.d -o CMakeFiles/l2learn_observer_util.dir/fboss/agent/test/utils/L2LearningUpdateObserverUtil.cpp.o -c /var/FBOSS/fboss/fboss/agent/test/utils/L2LearningUpdateObserverUtil.cpp
In file included from /var/FBOSS/fboss/fboss/agent/test/utils/L2LearningUpdateObserverUtil.h:7,
                 from /var/FBOSS/fboss/fboss/agent/test/utils/L2LearningUpdateObserverUtil.cpp:3:
/var/FBOSS/fboss/fboss/agent/test/AgentEnsemble.h:23:10: fatal error: fboss/agent/if/gen-cpp2/AgentHwTestCtrl.h: No such file or directory
   23 | #include "fboss/agent/if/gen-cpp2/AgentHwTestCtrl.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Reviewed By: shiva-menta

Differential Revision: D83856311

fbshipit-source-id: 8d6bdba28846f4db2476c0d1fe9917396ea9fc05