type cast to avoid different enum arithmetic errors in libusb
Summary:
As titled, type cast to avoid different enum arithmetic errors in libusb

This is towards enabling co-routines on FBOSS OSS + moving to C++20 + building sw and hw agent in OSS

Error seen:

```
error: arithmetic between different enumeration types
```

Reviewed By: shri-khare

Differential Revision: D50465462

fbshipit-source-id: db1374508e6f543710a08cd1b5c2ceccd4e63a97