Dockerfile.debian move install python3-pip earlier and allow global.break-system-packages
Summary:
Currently when building the docker container using Dockerfile.debian is broken because:
```
Processing triggers for libc-bin (2.36-9+deb12u10) ...
 ---
+ pip \
+      install \
+      pex
error running `pip \
+      install \
+      pex`: [Errno 2] No such file or directory: 'pip'Traceback (most recent call last):
  File "/var/FBOSS/fboss/build/fbcode_builder/getdeps/runcmd.py", line 109, in _run_cmd
    p = subprocess.Popen(
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/FBOSS/fboss/./build/fbcode_builder/getdeps.py", line 1603, in <module>
    sys.exit(main())
             ^^^^^^
  File "/var/FBOSS/fboss/./build/fbcode_builder/getdeps.py", line 1586, in main
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "/var/FBOSS/fboss/./build/fbcode_builder/getdeps.py", line 108, in run
    self.run_project_cmd(args, loader, manifest)
  File "/var/FBOSS/fboss/./build/fbcode_builder/getdeps.py", line 475, in run_project_cmd
    check_cmd(cmd_args)
  File "/var/FBOSS/fboss/build/fbcode_builder/getdeps/runcmd.py", line 47, in check_cmd
    rc = run_cmd(cmd, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/FBOSS/fboss/build/fbcode_builder/getdeps/runcmd.py", line 67, in run_cmd
    return _run_cmd(
           ^^^^^^^^^
  File "/var/FBOSS/fboss/build/fbcode_builder/getdeps/runcmd.py", line 114, in _run_cmd
    raise RunCommandError(
getdeps.runcmd.RunCommandError: [Errno 2] No such file or directory: 'pip' while running `pip \
+      install \
+      pex` with env=None
os.environ=environ({'HOSTNAME': '9579de3970e7', 'HOME': '/root', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'PWD': '/var/FBOSS/fboss', 'LC_CTYPE': 'C.UTF-8', 'GETDEPS_CMAKE_DEFINES': ''})
Error: building at STEP "RUN ./build/fbcode_builder/getdeps.py install-system-deps --recursive fboss": while running runtime: exit status 1
```

It seems like when installing fboss build dependencies, we need to use pip install pex. But before this change, we only install python3-pip very end of the actions.

I also had to temporarily enable allowing breaking system packages option for pip cause we can't control `pip install pex` in the Dockerfile as it triggers by one of the libraries installation. But I also make sure I change the option back to false to disable it. Without setting this global option for pip, we will hit the following error:
```
Processing triggers for libc-bin (2.36-9+deb12u10) ...
 ---
+ pip \
+      install \
+      pex
Command '['pip', 'install', 'pex']' returned non-zero exit status 1.
!! Failed
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Error: building at STEP "RUN ./build/fbcode_builder/getdeps.py install-system-deps --recursive fboss": while running runtime: exit status 1
```

Reviewed By: KevinYakar

Differential Revision: D79131789

fbshipit-source-id: aff57fb00e89d39835713a12662fb80e3a895888