Fix fmt library error for logging `sai_object_type_t`
Summary:
This hopefully 🤞 fixes the last of the errors plaguing the on-diff testing. Example failure from `fboss_fake_agent_targets`:

https://www.internalfb.com/sandcastle/workflow/229683581000493149

Error:

```
FAILED: CMakeFiles/sai_tracer.dir/fboss/agent/hw/sai/tracer/SaiTracer.cpp.o
/bin/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DGFLAGS_IS_A_DLL=0 -DIS_OSS=true -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fatal -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/nlohmann-json-V_y40AM2bw1iyK-EuS5vDcCNIvuQeSUE4e5YoBr-lB0/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/libsai-yESaIdbzrehcCGRJKe38Qag38dWOc6AfdCHIhidG9-w/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/libsai-yESaIdbzrehcCGRJKe38Qag38dWOc6AfdCHIhidG9-w/experimental -I/usr/include/libnl3 -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/iproute2-uZlREBVTwro6XgcS1k92RX1WsnBeZ-bwcHp9vBd4xeQ/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/yaml-cpp-qO3lWZVT4UgBNn_iIPaAGXVLKmz02GwHst9pmDKpm0o/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/libyaml-TY3Te3S5ejn-jjt3UP2vfLUbjC90dc6PD7psoP2Mts8/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/exprtk-hcCQcft-6V9VbQ8DMWtwvqa_bH2--mA2nUsf5WTabhA -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/libgpiod-OPLQYQVN3BoqYmnUWicqoIvh3LPVN0chmpoMHdVTED8/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/googletest-7JnJT5CgY1LVTPmQfwvncdoArZXAShZsSsQa9C0lCU4/include -I/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build/fboss -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/gflags-FHGtz15ipgdtBy8VDWwU07RNW_0yBukAYrcBYzpi1g8/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/glog-kCh757cr82SAdy4c1gcwKKJY2dg-eTnUsnnFYmqPNS4/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/folly/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/boost-ekzv3-LMUT7ciCQTZ8O6VgxUmubclRMMSvqk1pfNRpU/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fb303/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fast_float-hCKLOe4pzx88oAL9hVCAcLxBNK9i35cyIBeUAB-HrkE/include -isystem /usr/include/libdwarf-0 -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/wangle/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fizz/include -isystem /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/mvfst/include -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG -std=gnu++20 -DSAI_VER_MAJOR=1   -DSAI_VER_MINOR=14    -DSAI_VER_RELEASE=0 -fsized-deallocation -MD -MT CMakeFiles/sai_tracer.dir/fboss/agent/hw/sai/tracer/SaiTracer.cpp.o -MF CMakeFiles/sai_tracer.dir/fboss/agent/hw/sai/tracer/SaiTracer.cpp.o.d -o CMakeFiles/sai_tracer.dir/fboss/agent/hw/sai/tracer/SaiTracer.cpp.o -c /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/hw/sai/tracer/SaiTracer.cpp
In file included from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/format.h:41,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/folly/include/folly/Range.h:60,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/folly/include/folly/logging/xlog.h:23,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/SysError.h:12,
                 from /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/hw/sai/tracer/SaiTracer.cpp:16:
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h: In instantiation of ‘constexpr decltype (ctx.begin()) fmt::v11::detail::parse_format_specs(ParseContext&) [with T = _sai_object_type_t; ParseContext = fmt::v11::detail::compile_parse_context<char>; decltype (ctx.begin()) = const char*]’:
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2735:9:   required from ‘constexpr fmt::v11::detail::format_string_checker<Char, Args>::format_string_checker(fmt::v11::basic_string_view<Char>) [with Char = char; Args = {folly::Range<const char*>, _sai_object_type_t}]’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/folly/include/folly/container/MapUtil.h:105:33:   required from ‘typename Map::mapped_type& folly::get_or_throw(Map&, const Key&, const StringPiece&) [with E = std::out_of_range; Map = std::map<_sai_object_type_t, std::__cxx11::basic_string<char> >; Key = _sai_object_type_t; typename Map::mapped_type = std::__cxx11::basic_string<char>; folly::StringPiece = folly::Range<const char*>]’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/hw/sai/tracer/SaiTracer.cpp:596:26:   required from here
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/folly/include/folly/container/MapUtil.h:105:33:   in ‘constexpr’ expansion of ‘fmt::v11::basic_format_string<char, const folly::Range<const char*>&, const _sai_object_type_t&>("{}{}")’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2673:45: error: ‘fmt::v11::detail::type_is_unformattable_for<_sai_object_type_t, char> _’ has incomplete type
 2673 |     type_is_unformattable_for<T, char_type> _;
      |                                             ^
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/folly/include/folly/container/MapUtil.h: In instantiation of ‘typename Map::mapped_type& folly::get_or_throw(Map&, const Key&, const StringPiece&) [with E = std::out_of_range; Map = std::map<_sai_object_type_t, std::__cxx11::basic_string<char> >; Key = _sai_object_type_t; typename Map::mapped_type = std::__cxx11::basic_string<char>; folly::StringPiece = folly::Range<const char*>]’:
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/hw/sai/tracer/SaiTracer.cpp:596:26:   required from here
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/folly/include/folly/container/MapUtil.h:105:33:   in ‘constexpr’ expansion of ‘fmt::v11::basic_format_string<char, const folly::Range<const char*>&, const _sai_object_type_t&>("{}{}")’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2884:40:   in ‘constexpr’ expansion of ‘fmt::v11::detail::parse_format_string<true, char, fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t> >(((fmt::v11::basic_format_string<char, const folly::Range<const char*>&, const _sai_object_type_t&>*)this)->fmt::v11::basic_format_string<char, const folly::Range<const char*>&, const _sai_object_type_t&>::str_, fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t>(fmt::v11::basic_string_view<char>(((const char*)s))))’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2613:44:   in ‘constexpr’ expansion of ‘fmt::v11::detail::parse_replacement_field<char, fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t>&>((p + -1), end, (* & handler))’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2581:33:   in ‘constexpr’ expansion of ‘(& handler)->fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t>::on_replacement_field((& handler)->fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t>::on_arg_id(), begin)’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2756:20:   in ‘constexpr’ expansion of ‘((fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t>*)this)->fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t>::on_format_specs(id, begin, begin)’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2763:51: error: ‘constexpr decltype (ctx.begin()) fmt::v11::detail::parse_format_specs(ParseContext&) [with T = _sai_object_type_t; ParseContext = fmt::v11::detail::compile_parse_context<char>; decltype (ctx.begin()) = const char*]’ called in a constant expression
 2763 |     return id >= 0 && id < num_args ? parse_funcs_[id](context_) : begin;
      |                                       ~~~~~~~~~~~~^
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2660:20: note: ‘constexpr decltype (ctx.begin()) fmt::v11::detail::parse_format_specs(ParseContext&) [with T = _sai_object_type_t; ParseContext = fmt::v11::detail::compile_parse_context<char>; decltype (ctx.begin()) = const char*]’ is not usable as a ‘constexpr’ function because:
 2660 | FMT_CONSTEXPR auto parse_format_specs(ParseContext& ctx)
      |                    ^~~~~~~~~~~~~~~~~~
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/folly/include/folly/container/MapUtil.h: In instantiation of ‘typename Map::mapped_type& folly::get_or_throw(Map&, const Key&, const StringPiece&) [with E = std::out_of_range; Map = std::map<_sai_object_type_t, std::atomic<unsigned int> >; Key = _sai_object_type_t; typename Map::mapped_type = std::atomic<unsigned int>; folly::StringPiece = folly::Range<const char*>]’:
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fboss/fboss/agent/hw/sai/tracer/SaiTracer.cpp:1285:33:   required from here
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/folly/include/folly/container/MapUtil.h:105:33:   in ‘constexpr’ expansion of ‘fmt::v11::basic_format_string<char, const folly::Range<const char*>&, const _sai_object_type_t&>("{}{}")’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2884:40:   in ‘constexpr’ expansion of ‘fmt::v11::detail::parse_format_string<true, char, fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t> >(((fmt::v11::basic_format_string<char, const folly::Range<const char*>&, const _sai_object_type_t&>*)this)->fmt::v11::basic_format_string<char, const folly::Range<const char*>&, const _sai_object_type_t&>::str_, fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t>(fmt::v11::basic_string_view<char>(((const char*)s))))’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2613:44:   in ‘constexpr’ expansion of ‘fmt::v11::detail::parse_replacement_field<char, fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t>&>((p + -1), end, (* & handler))’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2581:33:   in ‘constexpr’ expansion of ‘(& handler)->fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t>::on_replacement_field((& handler)->fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t>::on_arg_id(), begin)’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2756:20:   in ‘constexpr’ expansion of ‘((fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t>*)this)->fmt::v11::detail::format_string_checker<char, folly::Range<const char*>, _sai_object_type_t>::on_format_specs(id, begin, begin)’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-r9NMexE5zOSTPootfGu7cmU9U5mIr4-9ibtXGRGuVwU/include/fmt/base.h:2763:51: error: ‘constexpr decltype (ctx.begin()) fmt::v11::detail::parse_format_specs(ParseContext&) [with T = _sai_object_type_t; ParseContext = fmt::v11::detail::compile_parse_context<char>; decltype (ctx.begin()) = const char*]’ called in a constant expression
 2763 |     return id >= 0 && id < num_args ? parse_funcs_[id](context_) : begin;
      |
```

**Context**:
The issue is that `fmt` lib requires some scaffolding in order to appropriately log "complex" types (being any type that is not defined in the standard library for C++). In this case, some code is formatting `sai_object_type_t`, so we need to add appropriate stubs for the default beahvior.

Reviewed By: harshitgulati18

Differential Revision: D64550065

fbshipit-source-id: 17f352e5bd9a1c2a14ed873389e95065ef984db0