Add 'hostname' package to FBOSS build container (#1131)
Summary:
**Pre-submission checklist**
- [x] I've ran the linters locally and fixed lint errors related to the files I modified in this PR. You can install the linters by running `pip install -r requirements-dev.txt && pre-commit install`
- [x] `pre-commit run`

The build container image was missing the `hostname` utility, requiring a manual `sudo dnf install hostname` after entering the container.

it was observed while trying to generate `asic_config_v2` ouput
```
./fboss/lib/asic_config_v2/run-helper.sh
...
...
FileNotFoundError: [Errno 2] No such file or directory: 'hostname'
```

In this PR:
- Install it at image-build time alongside the other packages.

Pull Request resolved: https://github.com/facebook/fboss/pull/1131

Test Plan:
Docker container built with new image contains `hostname` utility.
When `hostname` utility is available, `asic_config_v2/run-helper.sh` moves past this initial failure mentioned above in the description.

Reviewed By: Scott8440

Differential Revision: D108351751

Pulled By: joseph5wu

fbshipit-source-id: 199309b4e4799ca54083c0830bbd225cba0625d5