Fixing C++20 warnings and autodeps
Summary:
As titled. This also caused error in OSS.

Errors:
```
HwHashConsistencyTest.cpp:230:16: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
HwHashConsistencyTest.cpp:109:3: error: control reaches end of non-void function [-Werror=return-type]
```

Ran Autodeps:
```
[vsp@devvm5273.cln0 ~/fbsource/fbcode (59c75cb9e)]$ autodeps fboss/agent
```

Reviewed By: paulcruz74

Differential Revision: D71428530

fbshipit-source-id: adcfe33e436b1ce20010040ae04d7b5526b9ce38