Fix OSS build issue for "undefined reference"
Summary:
OSS builds for `fboss_hw_agent-sai_impl` currently fail due to the following error: P1539852319

```
HwTestAclUtilsThriftHandler.cpp:(.text+0x2414): undefined reference to `facebook::fboss::utility::getAclEntryByName(std::shared_ptr<facebook::fboss::SwitchState>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: HwTestAclUtilsThriftHandler.cpp:(.text+0x2453): undefined reference to `facebook::fboss::utility::getAclTrafficCounter(std::shared_ptr<facebook::fboss::SwitchState>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
[2345/2349] Building CXX object CMakeFiles/agent_hw_test_src.dir/fboss/agent/test/agent_hw_tests/AgentTrunkLoadBalancerTests.cpp.o
ninja: build stopped: subcommand failed.
Command '['/usr/bin/cmake', '--build', '/var/FBOSS/tmp_bld_dir/build/fboss', '--target', 'install', '--config', 'RelWithDebInfo', '-j', '32']' returned non-zero exit status 1.
!! Failed
```

`getAclTrafficCounter` is defined in https://fburl.com/code/3afvs9ag `AclTestUtils.cpp`, which gets built under https://fburl.com/code/r046ryop `acl_test_utils`

Reviewed By: srikrishnagopu

Differential Revision: D61631422

fbshipit-source-id: 983ef1da075fabaf805bbacc1f5009010fe5f6a0