SAI_VERSION should not be reliant on sai impl arg; correctly patch libsai manifest
Summary:
Fixed a bug where SAI VERSION is only getting updated if sai impl arg is provided, even though we edit the manifest file. The SAI_VERSION should be modifialbe with or without npu impl arg being provided.

Also fix a bug which was surfaced with this change which omits the word `experimental` when patching the libsai manifest file.

This has led to errors such as:
```
/var/FBOSS/tmp_bld_dir/installed/libsai-LGNrhB4a8uz5ObjgIiVDzcuk_N0-Nui7Co-3QQrDwj8/include/saiobject.h:41:10: fatal error: 'saiexperimentaldashtrustedvni.h' file not found
   41 | #include <saiexperimentaldashtrustedvni.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Reviewed By: joseph5wu

Differential Revision: D97673520

fbshipit-source-id: 6304ac90ddd36d915d3f2604b1e6acc6ad3df202