Support ModbusDeviceType.ORV3_BBU
Summary:
Newer wedge400 versions introduced `ORV3_BBU` objects but there was no corresponding struct on `rackmonsvc.thrift` causing this exception in Central Proxy:

```
[2023-02-07 13:19:42,144] ERROR: Error while trying to GET https://rsw045-oob.p058.f01.nha2.tfbnw.net:8443/api/sys/modbus/registers: KeyError('ORV3_BBU') (restapi.py:479)
Traceback (most recent call last):
  File "thrift.py3/types.pyx", line 635, in thrift.py3.types.EnumMeta.__getitem__
  File "rackmonsvc/types.pyx", line 191, in rackmonsvc.types.__ModbusDeviceTypeMeta.__getattribute__
  File "thrift.py3/types.pyx", line 510, in thrift.py3.types.EnumData.get_by_name
AttributeError: 'ModbusDeviceType' has no attribute 'ORV3_BBU'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "openbmc/lib/restapi.py", line 460, in get_rackdata_orv3
    ] = rackmonsvc.types.ModbusDeviceType[
  File "thrift.py3/types.pyx", line 637, in thrift.py3.types.EnumMeta.__getitem__
KeyError: 'ORV3_BBU'
```

Still working on unit tests and issue tasker coverage, will try landing this early to recover visibility on those devices.

Reviewed By: cjcon90

Differential Revision: D43120917

fbshipit-source-id: 2adb391f999d6d0282d4416721cb911913da2548