Fix build from missing thrift dep in fboss2 mpls
Summary:
D37757887 (https://github.com/facebook/fboss/commit/6c0366c45e77b6ff0cddd32b85ee7dec4f4dc3da) added this thrift file and buck has the thrift dep but looks like the cmake is missing the dep. Noticed error on D38720637

```
./fboss/cli/fboss2/commands/show/mpls/gen-cpp2/model_types.h:13:10: fatal error: fboss/cli/fboss2/commands/show/route/gen-cpp2/model_types.h: No such file or directory
 #include "fboss/cli/fboss2/commands/show/route/gen-cpp2/model_types.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Reviewed By: msomasundaran

Differential Revision: D38790072

fbshipit-source-id: 6fd96301b71e72753162bd9000fb7a6b0a27476d