include "this" in implicit lambda capture in sai next hop group handler
Summary:
As titled, include "this" in implicit lambda capture in sai next hop group handler

This is towards enabling co-routines on FBOSS OSS + moving to C++20 + building sw and hw agent in OSS

Error seen:
```
 error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20
```

Reviewed By: shri-khare

Differential Revision: D50465467

fbshipit-source-id: d513822dba83689e5b2d822e3c1e1dce49cdca53