include "this" in implicit lambda capture in hw switch
Summary:
As titled, include "this" in implicit lambda capture in hw switch

This is towards enabling co-routines on FBOSS OSS + moving to C++20 + building sw and hw agent in OSS

Error seen:
```
 error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20
```

Reviewed By: shri-khare

Differential Revision: D50465457

fbshipit-source-id: c22f9f2bc681eaf47c9bd2838b7f59be31ccd026