Update to use the cisco psu driver for morgan800cc which sets page 0 (#1184)
Summary:
**Pre-submission checklist**
- [ ] I've ran the linters locally and fixed lint errors related to the files I modified in this PR. You can install the linters by running `pip install -r requirements-dev.txt && pre-commit install`
- [ ] `pre-commit run`

Pull Request resolved: https://github.com/facebook/fboss/pull/1184

Test Plan:
1. platform_manager launched successfully: P2390928498
2. PSU driver is attached to devices successfully.
3. sensor_service works as expected:

[root@fboss326007397.snc1 ~]# ls /sys/bus/i2c/drivers/cisco-pmbus-psu/
2-0058  3-0058  bind  module  uevent  unbind
[root@fboss326007397.snc1 ~]# sensors cisco_psu-i2c-2-58
cisco_psu-i2c-2-58
Adapter: Cisco I2C SMB adapter at offset 0x3000
vin:         206.00 V
vout1:        12.03 V  (crit max = +128.00 V)
ERROR: Can't get value of subfeature in3_crit_alarm: Can't read
vout2:        12.01 V  (crit max = +128.00 V)
fan1:        12336 RPM
fan2:        11648 RPM
temp1:        +36.0°C  (high = +121.0°C)
temp2:        +61.0°C  (high = +121.0°C)
temp3:        +31.0°C  (high = +121.0°C)
pin:         260.00 W
pout1:       220.00 W
pout2:         1.60 W
iin:           1.28 A  (max = +20.00 A)
iout1:        18.28 A  (max = +288.00 A, crit max = +325.00 A)
ERROR: Can't get value of subfeature curr3_max_alarm: Can't read
ERROR: Can't get value of subfeature curr3_crit_alarm: Can't read
iout2:       132.00 mA (max = +288.00 A, crit max = +325.00 A)

[root@fboss326007397.snc1 ~]# sensors cisco_psu-i2c-3-58
cisco_psu-i2c-3-58
Adapter: Cisco I2C SMB adapter at offset 0x4000
vin:         206.25 V
vout1:        12.03 V  (crit max = +128.00 V)
ERROR: Can't get value of subfeature in3_crit_alarm: Can't read
vout2:        12.02 V  (crit max = +128.00 V)
fan1:        12656 RPM
fan2:        11856 RPM
temp1:        +37.0°C  (high = +121.0°C)
temp2:        +69.0°C  (high = +121.0°C)
temp3:        +31.0°C  (high = +121.0°C)
pin:         245.50 W
pout1:       206.50 W
pout2:         1.06 W
iin:           1.21 A  (max = +20.00 A)
iout1:        17.16 A  (max = +288.00 A, crit max = +325.00 A)
ERROR: Can't get value of subfeature curr3_max_alarm: Can't read
ERROR: Can't get value of subfeature curr3_crit_alarm: Can't read
iout2:        87.00 mA (max = +288.00 A, crit max = +325.00 A)

Slot Path: /PSU_SLOT@0:

+--------------+--------+--------+-------------------+------------+-------------+------------------------------------------------+
| name         | value  | status | criticalRange     | alarmRange | lastUpdated | sysfsPath                                      |
+--------------+--------+--------+-------------------+------------+-------------+------------------------------------------------+
| PSU0_IIN     | 1.28   | PASS   | [0.00, 80.00]     | [, ]       | 6s ago      | /run/devmap/sensors/PDB0_PSU_0X58/curr1_input  |
| PSU0_IOUT_MN | 18.22  | PASS   | [5.00, 250.00]    | [, ]       | 6s ago      | /run/devmap/sensors/PDB0_PSU_0X58/curr2_input  |
| PSU0_PIN_MN  | 260.00 | PASS   | [, ]              | [, ]       | 6s ago      | /run/devmap/sensors/PDB0_PSU_0X58/power1_input |
| PSU0_POUT_MN | 219.00 | PASS   | [60.00, 3,000.00] | [, ]       | 6s ago      | /run/devmap/sensors/PDB0_PSU_0X58/power2_input |
| PSU0_TMP1_MN | 36.00  | PASS   | [-5.00, 72.00]    | [, ]       | 6s ago      | /run/devmap/sensors/PDB0_PSU_0X58/temp1_input  |
| PSU0_TMP2_MN | 61.00  | PASS   | [-5.00, 102.00]   | [, ]       | 6s ago      | /run/devmap/sensors/PDB0_PSU_0X58/temp2_input  |
| PSU0_TMP3_MN | 30.00  | PASS   | [-5.00, 95.00]    | [, ]       | 6s ago      | /run/devmap/sensors/PDB0_PSU_0X58/temp3_input  |
| PSU0_VIN     | 206.00 | PASS   | [38.00, 407.00]   | [, ]       | 6s ago      | /run/devmap/sensors/PDB0_PSU_0X58/in1_input    |
| PSU0_VOUT_MN | 12.03  | PASS   | [9.60, 14.40]     | [, ]       | 6s ago      | /run/devmap/sensors/PDB0_PSU_0X58/in2_input    |
+--------------+--------+--------+-------------------+------------+-------------+------------------------------------------------+

Slot Path: /PSU_SLOT@1:

+--------------+--------+--------+-------------------+------------+-------------+------------------------------------------------+
| name         | value  | status | criticalRange     | alarmRange | lastUpdated | sysfsPath                                      |
+--------------+--------+--------+-------------------+------------+-------------+------------------------------------------------+
| PSU1_IIN     | 1.22   | PASS   | [0.00, 80.00]     | [, ]       | 6s ago      | /run/devmap/sensors/PDB1_PSU_0X58/curr1_input  |
| PSU1_IOUT_MN | 17.16  | PASS   | [5.00, 250.00]    | [, ]       | 6s ago      | /run/devmap/sensors/PDB1_PSU_0X58/curr2_input  |
| PSU1_PIN_MN  | 246.00 | PASS   | [, ]              | [, ]       | 6s ago      | /run/devmap/sensors/PDB1_PSU_0X58/power1_input |
| PSU1_POUT_MN | 206.50 | PASS   | [60.00, 3,000.00] | [, ]       | 6s ago      | /run/devmap/sensors/PDB1_PSU_0X58/power2_input |
| PSU1_TMP1_MN | 37.00  | PASS   | [-5.00, 72.00]    | [, ]       | 6s ago      | /run/devmap/sensors/PDB1_PSU_0X58/temp1_input  |
| PSU1_TMP2_MN | 69.00  | PASS   | [-5.00, 102.00]   | [, ]       | 6s ago      | /run/devmap/sensors/PDB1_PSU_0X58/temp2_input  |
| PSU1_TMP3_MN | 31.00  | PASS   | [-5.00, 95.00]    | [, ]       | 6s ago      | /run/devmap/sensors/PDB1_PSU_0X58/temp3_input  |
| PSU1_VIN     | 206.50 | PASS   | [38.00, 407.00]   | [, ]       | 6s ago      | /run/devmap/sensors/PDB1_PSU_0X58/in1_input    |
| PSU1_VOUT_MN | 12.03  | PASS   | [9.60, 14.40]     | [, ]       | 6s ago      | /run/devmap/sensors/PDB1_PSU_0X58/in2_input    |
+--------------+--------+--------+-------------------+------------+-------------+------------------------------------------------+

Reviewed By: somasun

Differential Revision: D104897034

Pulled By: tao-ren

fbshipit-source-id: 1e18e00f144356095785e24bd0667404d140da40