Include epdm headers into include_directories for cmake
Summary:
D101702131 needs to start using epdm.h directly in our qsfp_service code.
Unlike tp2, FBOSS OSS build needs to explicitly specify the header directories from SDK.
Only linking the SDK artifacts without include the header directories will cause FBOSS code won't be able to find the header like:
```
631 /var/FBOSS/fboss_src/fboss/qsfp_service/diag/XphyStatusDump.cpp:25:10: fatal error: 'epdm.h' file not found
632    25 | #include "epdm.h" // manual=//third-party/broadcom-plp-epdm:epdm
633       |          ^~~~~~~~
634 1 error generated.
```

This diff has three changes:
- CMakeLists.txt now will start including `/var/FBOSS/pai_impl/include/epdm` directory
- Update our Claude skill: prepare-brcm-pai-sdk build script template to automatically prepare the epdm header folder in `/var/FBOSS/pai_impl/include/epdm`
- Update our FBOSS build wiki to pick up the same change as we do for the claude skill script

Reviewed By: Protick666

Differential Revision: D102289893

fbshipit-source-id: 0102f427531c758dd5aa5b5931c05b46512477cd