include "this" in implicit lambda capture in RIB
Summary:
As titled, include "this" in implicit lambda capture in RIB

This is towards enabling co-routines on FBOSS OSS + moving to C++20 + building sw and hw agent in OSS

Error seen:
```
 error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20
```

Reviewed By: shri-khare

Differential Revision: D50465464

fbshipit-source-id: 9223abd71e539a58ec3b633c39b5d01ca30227da