Remove unused getCurrentTime() (breaking OSS builds)
Summary:
As titled - function is not in use and seeing the following error on OSS builds.

```
2025-08-21T10:13:47.0729491Z /var/FBOSS/fboss/fboss/agent/test/agent_hw_tests/AgentCoppTests.cpp:65:15: error: ‘time_t {anonymous}::getCurrentTime()’ defined but not used [-Werror=unused-function]
2025-08-21T10:13:47.0730807Z    65 | static time_t getCurrentTime() {
2025-08-21T10:13:47.0731234Z       |               ^~~~~~~~~~~~~~
```

Reviewed By: KevinYakar, harshitgulati18

Differential Revision: D80707860

fbshipit-source-id: 2f06037a924d3ed00fa0d4d56df85150afcd457b