include "this" in implicit lambda capture in next hop probe
Summary:
As titled,  include "this" in implicit lambda capture in next hop probe

This is towards enabling co-routines on FBOSS OSS + moving to C++20 + building sw and hw agent in OSS

Error seen:
```
 error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20
```

Reviewed By: shri-khare

Differential Revision: D50465459

fbshipit-source-id: 27a738f45e4090f321e01af98e43200a9bdcdad4